// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: INTERACT_WORD_V2.proto

package interactwordv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskPolicyEnum int32

const (
	RiskPolicyEnum_RP_NORMAL  RiskPolicyEnum = 0
	RiskPolicyEnum_RP_POLICY  RiskPolicyEnum = 1
	RiskPolicyEnum_RP_SILENCE RiskPolicyEnum = 2
	RiskPolicyEnum_RP_CNY     RiskPolicyEnum = 3
	RiskPolicyEnum_RP_BIGEV   RiskPolicyEnum = 4
)

// Enum value maps for RiskPolicyEnum.
var (
	RiskPolicyEnum_name = map[int32]string{
		0: "RP_NORMAL",
		1: "RP_POLICY",
		2: "RP_SILENCE",
		3: "RP_CNY",
		4: "RP_BIGEV",
	}
	RiskPolicyEnum_value = map[string]int32{
		"RP_NORMAL":  0,
		"RP_POLICY":  1,
		"RP_SILENCE": 2,
		"RP_CNY":     3,
		"RP_BIGEV":   4,
	}
)

func (x RiskPolicyEnum) Enum() *RiskPolicyEnum {
	p := new(RiskPolicyEnum)
	*p = x
	return p
}

func (x RiskPolicyEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskPolicyEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_INTERACT_WORD_V2_proto_enumTypes[0].Descriptor()
}

func (RiskPolicyEnum) Type() protoreflect.EnumType {
	return &file_INTERACT_WORD_V2_proto_enumTypes[0]
}

func (x RiskPolicyEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskPolicyEnum.Descriptor instead.
func (RiskPolicyEnum) EnumDescriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{0}
}

type MedalType int32

const (
	MedalType_Medal_Wear MedalType = 0
	MedalType_Medal_Spec MedalType = 1
)

// Enum value maps for MedalType.
var (
	MedalType_name = map[int32]string{
		0: "Medal_Wear",
		1: "Medal_Spec",
	}
	MedalType_value = map[string]int32{
		"Medal_Wear": 0,
		"Medal_Spec": 1,
	}
)

func (x MedalType) Enum() *MedalType {
	p := new(MedalType)
	*p = x
	return p
}

func (x MedalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MedalType) Descriptor() protoreflect.EnumDescriptor {
	return file_INTERACT_WORD_V2_proto_enumTypes[1].Descriptor()
}

func (MedalType) Type() protoreflect.EnumType {
	return &file_INTERACT_WORD_V2_proto_enumTypes[1]
}

func (x MedalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MedalType.Descriptor instead.
func (MedalType) EnumDescriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{1}
}

type HaveMedalType int32

const (
	HaveMedalType_Medal_Common HaveMedalType = 0
	HaveMedalType_Medal_Group  HaveMedalType = 1
)

// Enum value maps for HaveMedalType.
var (
	HaveMedalType_name = map[int32]string{
		0: "Medal_Common",
		1: "Medal_Group",
	}
	HaveMedalType_value = map[string]int32{
		"Medal_Common": 0,
		"Medal_Group":  1,
	}
)

func (x HaveMedalType) Enum() *HaveMedalType {
	p := new(HaveMedalType)
	*p = x
	return p
}

func (x HaveMedalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HaveMedalType) Descriptor() protoreflect.EnumDescriptor {
	return file_INTERACT_WORD_V2_proto_enumTypes[2].Descriptor()
}

func (HaveMedalType) Type() protoreflect.EnumType {
	return &file_INTERACT_WORD_V2_proto_enumTypes[2]
}

func (x HaveMedalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HaveMedalType.Descriptor instead.
func (HaveMedalType) EnumDescriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{2}
}

type RoomAnonTypeEnum int32

const (
	RoomAnonTypeEnum_RA_ALL          RoomAnonTypeEnum = 0
	RoomAnonTypeEnum_RA_With_Subject RoomAnonTypeEnum = 1
)

// Enum value maps for RoomAnonTypeEnum.
var (
	RoomAnonTypeEnum_name = map[int32]string{
		0: "RA_ALL",
		1: "RA_With_Subject",
	}
	RoomAnonTypeEnum_value = map[string]int32{
		"RA_ALL":          0,
		"RA_With_Subject": 1,
	}
)

func (x RoomAnonTypeEnum) Enum() *RoomAnonTypeEnum {
	p := new(RoomAnonTypeEnum)
	*p = x
	return p
}

func (x RoomAnonTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomAnonTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_INTERACT_WORD_V2_proto_enumTypes[3].Descriptor()
}

func (RoomAnonTypeEnum) Type() protoreflect.EnumType {
	return &file_INTERACT_WORD_V2_proto_enumTypes[3]
}

func (x RoomAnonTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomAnonTypeEnum.Descriptor instead.
func (RoomAnonTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{3}
}

type InteractWordV2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname          string                 `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	UnameColor     string                 `protobuf:"bytes,3,opt,name=uname_color,json=unameColor,proto3" json:"uname_color,omitempty"`
	Identities     []uint64               `protobuf:"varint,4,rep,packed,name=identities,proto3" json:"identities,omitempty"`
	MsgType        uint64                 `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Roomid         uint64                 `protobuf:"varint,6,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Score          uint64                 `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	FansMedal      *FansMedalInfo         `protobuf:"bytes,9,opt,name=fans_medal,json=fansMedal,proto3" json:"fans_medal,omitempty"`
	IsSpread       uint64                 `protobuf:"varint,10,opt,name=is_spread,json=isSpread,proto3" json:"is_spread,omitempty"`
	SpreadInfo     string                 `protobuf:"bytes,11,opt,name=spread_info,json=spreadInfo,proto3" json:"spread_info,omitempty"`
	Contribution   *ContributionInfo      `protobuf:"bytes,12,opt,name=contribution,proto3" json:"contribution,omitempty"`
	SpreadDesc     string                 `protobuf:"bytes,13,opt,name=spread_desc,json=spreadDesc,proto3" json:"spread_desc,omitempty"`
	TailIcon       uint64                 `protobuf:"varint,14,opt,name=tail_icon,json=tailIcon,proto3" json:"tail_icon,omitempty"`
	TriggerTime    uint64                 `protobuf:"varint,15,opt,name=trigger_time,json=triggerTime,proto3" json:"trigger_time,omitempty"`
	PrivilegeType  uint64                 `protobuf:"varint,16,opt,name=privilege_type,json=privilegeType,proto3" json:"privilege_type,omitempty"`
	CoreUserType   uint64                 `protobuf:"varint,17,opt,name=core_user_type,json=coreUserType,proto3" json:"core_user_type,omitempty"`
	TailText       string                 `protobuf:"bytes,18,opt,name=tail_text,json=tailText,proto3" json:"tail_text,omitempty"`
	ContributionV2 *ContributionInfoV2    `protobuf:"bytes,19,opt,name=contribution_v2,json=contributionV2,proto3" json:"contribution_v2,omitempty"`
	GroupMedal     *GroupMedalBrief       `protobuf:"bytes,20,opt,name=group_medal,json=groupMedal,proto3" json:"group_medal,omitempty"`
	IsMystery      bool                   `protobuf:"varint,21,opt,name=is_mystery,json=isMystery,proto3" json:"is_mystery,omitempty"`
	Uinfo          *UserInfo              `protobuf:"bytes,22,opt,name=uinfo,proto3" json:"uinfo,omitempty"`
	RelationTail   *UserAnchorRelation    `protobuf:"bytes,23,opt,name=relation_tail,json=relationTail,proto3" json:"relation_tail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InteractWordV2) Reset() {
	*x = InteractWordV2{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractWordV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractWordV2) ProtoMessage() {}

func (x *InteractWordV2) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractWordV2.ProtoReflect.Descriptor instead.
func (*InteractWordV2) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{0}
}

func (x *InteractWordV2) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InteractWordV2) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *InteractWordV2) GetUnameColor() string {
	if x != nil {
		return x.UnameColor
	}
	return ""
}

func (x *InteractWordV2) GetIdentities() []uint64 {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *InteractWordV2) GetMsgType() uint64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *InteractWordV2) GetRoomid() uint64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *InteractWordV2) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InteractWordV2) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *InteractWordV2) GetFansMedal() *FansMedalInfo {
	if x != nil {
		return x.FansMedal
	}
	return nil
}

func (x *InteractWordV2) GetIsSpread() uint64 {
	if x != nil {
		return x.IsSpread
	}
	return 0
}

func (x *InteractWordV2) GetSpreadInfo() string {
	if x != nil {
		return x.SpreadInfo
	}
	return ""
}

func (x *InteractWordV2) GetContribution() *ContributionInfo {
	if x != nil {
		return x.Contribution
	}
	return nil
}

func (x *InteractWordV2) GetSpreadDesc() string {
	if x != nil {
		return x.SpreadDesc
	}
	return ""
}

func (x *InteractWordV2) GetTailIcon() uint64 {
	if x != nil {
		return x.TailIcon
	}
	return 0
}

func (x *InteractWordV2) GetTriggerTime() uint64 {
	if x != nil {
		return x.TriggerTime
	}
	return 0
}

func (x *InteractWordV2) GetPrivilegeType() uint64 {
	if x != nil {
		return x.PrivilegeType
	}
	return 0
}

func (x *InteractWordV2) GetCoreUserType() uint64 {
	if x != nil {
		return x.CoreUserType
	}
	return 0
}

func (x *InteractWordV2) GetTailText() string {
	if x != nil {
		return x.TailText
	}
	return ""
}

func (x *InteractWordV2) GetContributionV2() *ContributionInfoV2 {
	if x != nil {
		return x.ContributionV2
	}
	return nil
}

func (x *InteractWordV2) GetGroupMedal() *GroupMedalBrief {
	if x != nil {
		return x.GroupMedal
	}
	return nil
}

func (x *InteractWordV2) GetIsMystery() bool {
	if x != nil {
		return x.IsMystery
	}
	return false
}

func (x *InteractWordV2) GetUinfo() *UserInfo {
	if x != nil {
		return x.Uinfo
	}
	return nil
}

func (x *InteractWordV2) GetRelationTail() *UserAnchorRelation {
	if x != nil {
		return x.RelationTail
	}
	return nil
}

type ContributionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         int64                  `protobuf:"varint,1,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionInfo) Reset() {
	*x = ContributionInfo{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionInfo) ProtoMessage() {}

func (x *ContributionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionInfo.ProtoReflect.Descriptor instead.
func (*ContributionInfo) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{1}
}

func (x *ContributionInfo) GetGrade() int64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

type ContributionInfoV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         uint64                 `protobuf:"varint,1,opt,name=grade,proto3" json:"grade,omitempty"`
	RankType      string                 `protobuf:"bytes,2,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionInfoV2) Reset() {
	*x = ContributionInfoV2{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionInfoV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionInfoV2) ProtoMessage() {}

func (x *ContributionInfoV2) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionInfoV2.ProtoReflect.Descriptor instead.
func (*ContributionInfoV2) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{2}
}

func (x *ContributionInfoV2) GetGrade() uint64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *ContributionInfoV2) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *ContributionInfoV2) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FansMedalInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetId         int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MedalLevel       int64                  `protobuf:"varint,2,opt,name=medal_level,json=medalLevel,proto3" json:"medal_level,omitempty"`
	MedalName        string                 `protobuf:"bytes,3,opt,name=medal_name,json=medalName,proto3" json:"medal_name,omitempty"`
	MedalColor       int64                  `protobuf:"varint,4,opt,name=medal_color,json=medalColor,proto3" json:"medal_color,omitempty"`
	MedalColorStart  int64                  `protobuf:"varint,5,opt,name=medal_color_start,json=medalColorStart,proto3" json:"medal_color_start,omitempty"`
	MedalColorEnd    int64                  `protobuf:"varint,6,opt,name=medal_color_end,json=medalColorEnd,proto3" json:"medal_color_end,omitempty"`
	MedalColorBorder int64                  `protobuf:"varint,7,opt,name=medal_color_border,json=medalColorBorder,proto3" json:"medal_color_border,omitempty"`
	IsLighted        int64                  `protobuf:"varint,8,opt,name=is_lighted,json=isLighted,proto3" json:"is_lighted,omitempty"`
	GuardLevel       int64                  `protobuf:"varint,9,opt,name=guard_level,json=guardLevel,proto3" json:"guard_level,omitempty"`
	Special          string                 `protobuf:"bytes,10,opt,name=special,proto3" json:"special,omitempty"`
	IconId           int64                  `protobuf:"varint,11,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"`
	AnchorRoomid     int64                  `protobuf:"varint,12,opt,name=anchor_roomid,json=anchorRoomid,proto3" json:"anchor_roomid,omitempty"`
	Score            int64                  `protobuf:"varint,13,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FansMedalInfo) Reset() {
	*x = FansMedalInfo{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansMedalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansMedalInfo) ProtoMessage() {}

func (x *FansMedalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansMedalInfo.ProtoReflect.Descriptor instead.
func (*FansMedalInfo) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{3}
}

func (x *FansMedalInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *FansMedalInfo) GetMedalLevel() int64 {
	if x != nil {
		return x.MedalLevel
	}
	return 0
}

func (x *FansMedalInfo) GetMedalName() string {
	if x != nil {
		return x.MedalName
	}
	return ""
}

func (x *FansMedalInfo) GetMedalColor() int64 {
	if x != nil {
		return x.MedalColor
	}
	return 0
}

func (x *FansMedalInfo) GetMedalColorStart() int64 {
	if x != nil {
		return x.MedalColorStart
	}
	return 0
}

func (x *FansMedalInfo) GetMedalColorEnd() int64 {
	if x != nil {
		return x.MedalColorEnd
	}
	return 0
}

func (x *FansMedalInfo) GetMedalColorBorder() int64 {
	if x != nil {
		return x.MedalColorBorder
	}
	return 0
}

func (x *FansMedalInfo) GetIsLighted() int64 {
	if x != nil {
		return x.IsLighted
	}
	return 0
}

func (x *FansMedalInfo) GetGuardLevel() int64 {
	if x != nil {
		return x.GuardLevel
	}
	return 0
}

func (x *FansMedalInfo) GetSpecial() string {
	if x != nil {
		return x.Special
	}
	return ""
}

func (x *FansMedalInfo) GetIconId() int64 {
	if x != nil {
		return x.IconId
	}
	return 0
}

func (x *FansMedalInfo) GetAnchorRoomid() int64 {
	if x != nil {
		return x.AnchorRoomid
	}
	return 0
}

func (x *FansMedalInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UserAnchorRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TailIcon      string                 `protobuf:"bytes,1,opt,name=tail_icon,json=tailIcon,proto3" json:"tail_icon,omitempty"`
	TailGuideText string                 `protobuf:"bytes,2,opt,name=tail_guide_text,json=tailGuideText,proto3" json:"tail_guide_text,omitempty"`
	TailType      uint64                 `protobuf:"varint,3,opt,name=tail_type,json=tailType,proto3" json:"tail_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAnchorRelation) Reset() {
	*x = UserAnchorRelation{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnchorRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnchorRelation) ProtoMessage() {}

func (x *UserAnchorRelation) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnchorRelation.ProtoReflect.Descriptor instead.
func (*UserAnchorRelation) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{4}
}

func (x *UserAnchorRelation) GetTailIcon() string {
	if x != nil {
		return x.TailIcon
	}
	return ""
}

func (x *UserAnchorRelation) GetTailGuideText() string {
	if x != nil {
		return x.TailGuideText
	}
	return ""
}

func (x *UserAnchorRelation) GetTailType() uint64 {
	if x != nil {
		return x.TailType
	}
	return 0
}

type GroupMedalBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedalId       uint64                 `protobuf:"varint,1,opt,name=medal_id,json=medalId,proto3" json:"medal_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsLighted     uint64                 `protobuf:"varint,3,opt,name=is_lighted,json=isLighted,proto3" json:"is_lighted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMedalBrief) Reset() {
	*x = GroupMedalBrief{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMedalBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMedalBrief) ProtoMessage() {}

func (x *GroupMedalBrief) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMedalBrief.ProtoReflect.Descriptor instead.
func (*GroupMedalBrief) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{5}
}

func (x *GroupMedalBrief) GetMedalId() uint64 {
	if x != nil {
		return x.MedalId
	}
	return 0
}

func (x *GroupMedalBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupMedalBrief) GetIsLighted() uint64 {
	if x != nil {
		return x.IsLighted
	}
	return 0
}

type RiskCtrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Policy        RiskPolicyEnum         `protobuf:"varint,2,opt,name=policy,proto3,enum=bilibili.interact_word_v2.RiskPolicyEnum" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskCtrl) Reset() {
	*x = RiskCtrl{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskCtrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskCtrl) ProtoMessage() {}

func (x *RiskCtrl) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskCtrl.ProtoReflect.Descriptor instead.
func (*RiskCtrl) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{6}
}

func (x *RiskCtrl) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RiskCtrl) GetPolicy() RiskPolicyEnum {
	if x != nil {
		return x.Policy
	}
	return RiskPolicyEnum_RP_NORMAL
}

type RoomAnonCtrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RoomAnonTypeEnum       `protobuf:"varint,1,opt,name=type,proto3,enum=bilibili.interact_word_v2.RoomAnonTypeEnum" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomAnonCtrl) Reset() {
	*x = RoomAnonCtrl{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomAnonCtrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAnonCtrl) ProtoMessage() {}

func (x *RoomAnonCtrl) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAnonCtrl.ProtoReflect.Descriptor instead.
func (*RoomAnonCtrl) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{7}
}

func (x *RoomAnonCtrl) GetType() RoomAnonTypeEnum {
	if x != nil {
		return x.Type
	}
	return RoomAnonTypeEnum_RA_ALL
}

type BaseOption struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NeedMystery     bool                   `protobuf:"varint,1,opt,name=need_mystery,json=needMystery,proto3" json:"need_mystery,omitempty"`
	RiskCtrl        *RiskCtrl              `protobuf:"bytes,2,opt,name=risk_ctrl,json=riskCtrl,proto3" json:"risk_ctrl,omitempty"`
	RoomAnonCtrl    *RoomAnonCtrl          `protobuf:"bytes,3,opt,name=room_anon_ctrl,json=roomAnonCtrl,proto3" json:"room_anon_ctrl,omitempty"`
	RiskCtrlHandles []RiskPolicyEnum       `protobuf:"varint,4,rep,packed,name=risk_ctrl_handles,json=riskCtrlHandles,proto3,enum=bilibili.interact_word_v2.RiskPolicyEnum" json:"risk_ctrl_handles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseOption) Reset() {
	*x = BaseOption{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseOption) ProtoMessage() {}

func (x *BaseOption) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseOption.ProtoReflect.Descriptor instead.
func (*BaseOption) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{8}
}

func (x *BaseOption) GetNeedMystery() bool {
	if x != nil {
		return x.NeedMystery
	}
	return false
}

func (x *BaseOption) GetRiskCtrl() *RiskCtrl {
	if x != nil {
		return x.RiskCtrl
	}
	return nil
}

func (x *BaseOption) GetRoomAnonCtrl() *RoomAnonCtrl {
	if x != nil {
		return x.RoomAnonCtrl
	}
	return nil
}

func (x *BaseOption) GetRiskCtrlHandles() []RiskPolicyEnum {
	if x != nil {
		return x.RiskCtrlHandles
	}
	return nil
}

type GuardOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ruid          int64                  `protobuf:"varint,1,opt,name=ruid,proto3" json:"ruid,omitempty"`
	UseLocalCache bool                   `protobuf:"varint,2,opt,name=use_local_cache,json=useLocalCache,proto3" json:"use_local_cache,omitempty"`
	StrongDepend  bool                   `protobuf:"varint,3,opt,name=strong_depend,json=strongDepend,proto3" json:"strong_depend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardOption) Reset() {
	*x = GuardOption{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardOption) ProtoMessage() {}

func (x *GuardOption) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardOption.ProtoReflect.Descriptor instead.
func (*GuardOption) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{9}
}

func (x *GuardOption) GetRuid() int64 {
	if x != nil {
		return x.Ruid
	}
	return 0
}

func (x *GuardOption) GetUseLocalCache() bool {
	if x != nil {
		return x.UseLocalCache
	}
	return false
}

func (x *GuardOption) GetStrongDepend() bool {
	if x != nil {
		return x.StrongDepend
	}
	return false
}

type WealthOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roomid        int64                  `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	ViewUid       int64                  `protobuf:"varint,2,opt,name=view_uid,json=viewUid,proto3" json:"view_uid,omitempty"`
	Ruid          int64                  `protobuf:"varint,3,opt,name=ruid,proto3" json:"ruid,omitempty"`
	StrongDepend  bool                   `protobuf:"varint,4,opt,name=strong_depend,json=strongDepend,proto3" json:"strong_depend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WealthOption) Reset() {
	*x = WealthOption{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WealthOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WealthOption) ProtoMessage() {}

func (x *WealthOption) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WealthOption.ProtoReflect.Descriptor instead.
func (*WealthOption) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{10}
}

func (x *WealthOption) GetRoomid() int64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *WealthOption) GetViewUid() int64 {
	if x != nil {
		return x.ViewUid
	}
	return 0
}

func (x *WealthOption) GetRuid() int64 {
	if x != nil {
		return x.Ruid
	}
	return 0
}

func (x *WealthOption) GetStrongDepend() bool {
	if x != nil {
		return x.StrongDepend
	}
	return false
}

type MedalOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Typ           MedalType              `protobuf:"varint,1,opt,name=typ,proto3,enum=bilibili.interact_word_v2.MedalType" json:"typ,omitempty"`
	RoomId        int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	NeedGuard     bool                   `protobuf:"varint,3,opt,name=need_guard,json=needGuard,proto3" json:"need_guard,omitempty"`
	StrongDepend  bool                   `protobuf:"varint,4,opt,name=strong_depend,json=strongDepend,proto3" json:"strong_depend,omitempty"`
	NeedGroup     bool                   `protobuf:"varint,5,opt,name=need_group,json=needGroup,proto3" json:"need_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedalOption) Reset() {
	*x = MedalOption{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedalOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedalOption) ProtoMessage() {}

func (x *MedalOption) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedalOption.ProtoReflect.Descriptor instead.
func (*MedalOption) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{11}
}

func (x *MedalOption) GetTyp() MedalType {
	if x != nil {
		return x.Typ
	}
	return MedalType_Medal_Wear
}

func (x *MedalOption) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MedalOption) GetNeedGuard() bool {
	if x != nil {
		return x.NeedGuard
	}
	return false
}

func (x *MedalOption) GetStrongDepend() bool {
	if x != nil {
		return x.StrongDepend
	}
	return false
}

func (x *MedalOption) GetNeedGroup() bool {
	if x != nil {
		return x.NeedGroup
	}
	return false
}

type GuardLeaderOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ruid          int64                  `protobuf:"varint,1,opt,name=ruid,proto3" json:"ruid,omitempty"`
	RoomId        int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardLeaderOption) Reset() {
	*x = GuardLeaderOption{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardLeaderOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardLeaderOption) ProtoMessage() {}

func (x *GuardLeaderOption) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardLeaderOption.ProtoReflect.Descriptor instead.
func (*GuardLeaderOption) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{12}
}

func (x *GuardLeaderOption) GetRuid() int64 {
	if x != nil {
		return x.Ruid
	}
	return 0
}

func (x *GuardLeaderOption) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type TitleOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RooomId       int64                  `protobuf:"varint,1,opt,name=rooom_id,json=rooomId,proto3" json:"rooom_id,omitempty"`
	StrongDepend  bool                   `protobuf:"varint,2,opt,name=strong_depend,json=strongDepend,proto3" json:"strong_depend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleOption) Reset() {
	*x = TitleOption{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleOption) ProtoMessage() {}

func (x *TitleOption) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleOption.ProtoReflect.Descriptor instead.
func (*TitleOption) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{13}
}

func (x *TitleOption) GetRooomId() int64 {
	if x != nil {
		return x.RooomId
	}
	return 0
}

func (x *TitleOption) GetStrongDepend() bool {
	if x != nil {
		return x.StrongDepend
	}
	return false
}

type RiskCtrlInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Face          string                 `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskCtrlInfo) Reset() {
	*x = RiskCtrlInfo{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskCtrlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskCtrlInfo) ProtoMessage() {}

func (x *RiskCtrlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskCtrlInfo.ProtoReflect.Descriptor instead.
func (*RiskCtrlInfo) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{14}
}

func (x *RiskCtrlInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiskCtrlInfo) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

type AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Face          string                 `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{15}
}

func (x *AccountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountInfo) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

type OfficialInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          uint64                 `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Type          uint64                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfficialInfo) Reset() {
	*x = OfficialInfo{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfficialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficialInfo) ProtoMessage() {}

func (x *OfficialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficialInfo.ProtoReflect.Descriptor instead.
func (*OfficialInfo) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{16}
}

func (x *OfficialInfo) GetRole() uint64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *OfficialInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OfficialInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *OfficialInfo) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Face          string                 `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	NameColor     int32                  `protobuf:"varint,3,opt,name=name_color,json=nameColor,proto3" json:"name_color,omitempty"`
	IsMystery     bool                   `protobuf:"varint,4,opt,name=is_mystery,json=isMystery,proto3" json:"is_mystery,omitempty"`
	RiskCtrlInfo  *RiskCtrlInfo          `protobuf:"bytes,5,opt,name=risk_ctrl_info,json=riskCtrlInfo,proto3" json:"risk_ctrl_info,omitempty"`
	OriginInfo    *AccountInfo           `protobuf:"bytes,6,opt,name=origin_info,json=originInfo,proto3" json:"origin_info,omitempty"`
	OfficialInfo  *OfficialInfo          `protobuf:"bytes,7,opt,name=official_info,json=officialInfo,proto3" json:"official_info,omitempty"`
	NameColorStr  string                 `protobuf:"bytes,8,opt,name=name_color_str,json=nameColorStr,proto3" json:"name_color_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{17}
}

func (x *Base) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Base) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *Base) GetNameColor() int32 {
	if x != nil {
		return x.NameColor
	}
	return 0
}

func (x *Base) GetIsMystery() bool {
	if x != nil {
		return x.IsMystery
	}
	return false
}

func (x *Base) GetRiskCtrlInfo() *RiskCtrlInfo {
	if x != nil {
		return x.RiskCtrlInfo
	}
	return nil
}

func (x *Base) GetOriginInfo() *AccountInfo {
	if x != nil {
		return x.OriginInfo
	}
	return nil
}

func (x *Base) GetOfficialInfo() *OfficialInfo {
	if x != nil {
		return x.OfficialInfo
	}
	return nil
}

func (x *Base) GetNameColorStr() string {
	if x != nil {
		return x.NameColorStr
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Base          *Base                  `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Medal         *Medal                 `protobuf:"bytes,3,opt,name=medal,proto3" json:"medal,omitempty"`
	Wealth        *Wealth                `protobuf:"bytes,4,opt,name=wealth,proto3" json:"wealth,omitempty"`
	Title         *Title                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Guard         *Guard                 `protobuf:"bytes,6,opt,name=guard,proto3" json:"guard,omitempty"`
	UheadFrame    *UserHeadFrame         `protobuf:"bytes,7,opt,name=uhead_frame,json=uheadFrame,proto3" json:"uhead_frame,omitempty"`
	GuardLeader   *GuardLeader           `protobuf:"bytes,8,opt,name=guard_leader,json=guardLeader,proto3" json:"guard_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{18}
}

func (x *UserInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UserInfo) GetMedal() *Medal {
	if x != nil {
		return x.Medal
	}
	return nil
}

func (x *UserInfo) GetWealth() *Wealth {
	if x != nil {
		return x.Wealth
	}
	return nil
}

func (x *UserInfo) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UserInfo) GetGuard() *Guard {
	if x != nil {
		return x.Guard
	}
	return nil
}

func (x *UserInfo) GetUheadFrame() *UserHeadFrame {
	if x != nil {
		return x.UheadFrame
	}
	return nil
}

func (x *UserInfo) GetGuardLeader() *GuardLeader {
	if x != nil {
		return x.GuardLeader
	}
	return nil
}

type Medal struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level              int64                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	ColorStart         int64                  `protobuf:"varint,3,opt,name=color_start,json=colorStart,proto3" json:"color_start,omitempty"`
	ColorEnd           int64                  `protobuf:"varint,4,opt,name=color_end,json=colorEnd,proto3" json:"color_end,omitempty"`
	ColorBorder        int64                  `protobuf:"varint,5,opt,name=color_border,json=colorBorder,proto3" json:"color_border,omitempty"`
	Color              int64                  `protobuf:"varint,6,opt,name=color,proto3" json:"color,omitempty"`
	Id                 int64                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	Typ                HaveMedalType          `protobuf:"varint,8,opt,name=typ,proto3,enum=bilibili.interact_word_v2.HaveMedalType" json:"typ,omitempty"`
	IsLight            int64                  `protobuf:"varint,9,opt,name=is_light,json=isLight,proto3" json:"is_light,omitempty"`
	Ruid               int64                  `protobuf:"varint,10,opt,name=ruid,proto3" json:"ruid,omitempty"`
	GuardLevel         int64                  `protobuf:"varint,11,opt,name=guard_level,json=guardLevel,proto3" json:"guard_level,omitempty"`
	Score              int64                  `protobuf:"varint,12,opt,name=score,proto3" json:"score,omitempty"`
	GuardIcon          string                 `protobuf:"bytes,13,opt,name=guard_icon,json=guardIcon,proto3" json:"guard_icon,omitempty"`
	HonorIcon          string                 `protobuf:"bytes,14,opt,name=honor_icon,json=honorIcon,proto3" json:"honor_icon,omitempty"`
	V2MedalColorStart  string                 `protobuf:"bytes,15,opt,name=v2_medal_color_start,json=v2MedalColorStart,proto3" json:"v2_medal_color_start,omitempty"`
	V2MedalColorEnd    string                 `protobuf:"bytes,16,opt,name=v2_medal_color_end,json=v2MedalColorEnd,proto3" json:"v2_medal_color_end,omitempty"`
	V2MedalColorBorder string                 `protobuf:"bytes,17,opt,name=v2_medal_color_border,json=v2MedalColorBorder,proto3" json:"v2_medal_color_border,omitempty"`
	V2MedalColorText   string                 `protobuf:"bytes,18,opt,name=v2_medal_color_text,json=v2MedalColorText,proto3" json:"v2_medal_color_text,omitempty"`
	V2MedalColorLevel  string                 `protobuf:"bytes,19,opt,name=v2_medal_color_level,json=v2MedalColorLevel,proto3" json:"v2_medal_color_level,omitempty"`
	UserReceiveCount   int64                  `protobuf:"varint,20,opt,name=user_receive_count,json=userReceiveCount,proto3" json:"user_receive_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Medal) Reset() {
	*x = Medal{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Medal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Medal) ProtoMessage() {}

func (x *Medal) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Medal.ProtoReflect.Descriptor instead.
func (*Medal) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{19}
}

func (x *Medal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Medal) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Medal) GetColorStart() int64 {
	if x != nil {
		return x.ColorStart
	}
	return 0
}

func (x *Medal) GetColorEnd() int64 {
	if x != nil {
		return x.ColorEnd
	}
	return 0
}

func (x *Medal) GetColorBorder() int64 {
	if x != nil {
		return x.ColorBorder
	}
	return 0
}

func (x *Medal) GetColor() int64 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Medal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Medal) GetTyp() HaveMedalType {
	if x != nil {
		return x.Typ
	}
	return HaveMedalType_Medal_Common
}

func (x *Medal) GetIsLight() int64 {
	if x != nil {
		return x.IsLight
	}
	return 0
}

func (x *Medal) GetRuid() int64 {
	if x != nil {
		return x.Ruid
	}
	return 0
}

func (x *Medal) GetGuardLevel() int64 {
	if x != nil {
		return x.GuardLevel
	}
	return 0
}

func (x *Medal) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Medal) GetGuardIcon() string {
	if x != nil {
		return x.GuardIcon
	}
	return ""
}

func (x *Medal) GetHonorIcon() string {
	if x != nil {
		return x.HonorIcon
	}
	return ""
}

func (x *Medal) GetV2MedalColorStart() string {
	if x != nil {
		return x.V2MedalColorStart
	}
	return ""
}

func (x *Medal) GetV2MedalColorEnd() string {
	if x != nil {
		return x.V2MedalColorEnd
	}
	return ""
}

func (x *Medal) GetV2MedalColorBorder() string {
	if x != nil {
		return x.V2MedalColorBorder
	}
	return ""
}

func (x *Medal) GetV2MedalColorText() string {
	if x != nil {
		return x.V2MedalColorText
	}
	return ""
}

func (x *Medal) GetV2MedalColorLevel() string {
	if x != nil {
		return x.V2MedalColorLevel
	}
	return ""
}

func (x *Medal) GetUserReceiveCount() int64 {
	if x != nil {
		return x.UserReceiveCount
	}
	return 0
}

type Wealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int64                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	DmIconKey     string                 `protobuf:"bytes,2,opt,name=dm_icon_key,json=dmIconKey,proto3" json:"dm_icon_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wealth) Reset() {
	*x = Wealth{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wealth) ProtoMessage() {}

func (x *Wealth) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wealth.ProtoReflect.Descriptor instead.
func (*Wealth) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{20}
}

func (x *Wealth) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Wealth) GetDmIconKey() string {
	if x != nil {
		return x.DmIconKey
	}
	return ""
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldTitleCssId string                 `protobuf:"bytes,1,opt,name=OldTitleCssId,proto3" json:"OldTitleCssId,omitempty"`
	TitleCssId    string                 `protobuf:"bytes,2,opt,name=TitleCssId,proto3" json:"TitleCssId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{21}
}

func (x *Title) GetOldTitleCssId() string {
	if x != nil {
		return x.OldTitleCssId
	}
	return ""
}

func (x *Title) GetTitleCssId() string {
	if x != nil {
		return x.TitleCssId
	}
	return ""
}

type Guard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int64                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	ExpiredStr    string                 `protobuf:"bytes,2,opt,name=expired_str,json=expiredStr,proto3" json:"expired_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guard) Reset() {
	*x = Guard{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guard) ProtoMessage() {}

func (x *Guard) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guard.ProtoReflect.Descriptor instead.
func (*Guard) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{22}
}

func (x *Guard) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Guard) GetExpiredStr() string {
	if x != nil {
		return x.ExpiredStr
	}
	return ""
}

type UserHeadFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FrameImg      string                 `protobuf:"bytes,2,opt,name=frame_img,json=frameImg,proto3" json:"frame_img,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserHeadFrame) Reset() {
	*x = UserHeadFrame{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHeadFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHeadFrame) ProtoMessage() {}

func (x *UserHeadFrame) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHeadFrame.ProtoReflect.Descriptor instead.
func (*UserHeadFrame) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{23}
}

func (x *UserHeadFrame) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserHeadFrame) GetFrameImg() string {
	if x != nil {
		return x.FrameImg
	}
	return ""
}

type GuardLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsGuardLeader bool                   `protobuf:"varint,1,opt,name=is_guard_leader,json=isGuardLeader,proto3" json:"is_guard_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardLeader) Reset() {
	*x = GuardLeader{}
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardLeader) ProtoMessage() {}

func (x *GuardLeader) ProtoReflect() protoreflect.Message {
	mi := &file_INTERACT_WORD_V2_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardLeader.ProtoReflect.Descriptor instead.
func (*GuardLeader) Descriptor() ([]byte, []int) {
	return file_INTERACT_WORD_V2_proto_rawDescGZIP(), []int{24}
}

func (x *GuardLeader) GetIsGuardLeader() bool {
	if x != nil {
		return x.IsGuardLeader
	}
	return false
}

var File_INTERACT_WORD_V2_proto protoreflect.FileDescriptor

const file_INTERACT_WORD_V2_proto_rawDesc = "" +
	"\n" +
	"\x16INTERACT_WORD_V2.proto\x12\x19bilibili.interact_word_v2\"\xd6\a\n" +
	"\x0eInteractWordV2\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05uname\x18\x02 \x01(\tR\x05uname\x12\x1f\n" +
	"\vuname_color\x18\x03 \x01(\tR\n" +
	"unameColor\x12\x1e\n" +
	"\n" +
	"identities\x18\x04 \x03(\x04R\n" +
	"identities\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x04R\amsgType\x12\x16\n" +
	"\x06roomid\x18\x06 \x01(\x04R\x06roomid\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05score\x18\b \x01(\x04R\x05score\x12G\n" +
	"\n" +
	"fans_medal\x18\t \x01(\v2(.bilibili.interact_word_v2.FansMedalInfoR\tfansMedal\x12\x1b\n" +
	"\tis_spread\x18\n" +
	" \x01(\x04R\bisSpread\x12\x1f\n" +
	"\vspread_info\x18\v \x01(\tR\n" +
	"spreadInfo\x12O\n" +
	"\fcontribution\x18\f \x01(\v2+.bilibili.interact_word_v2.ContributionInfoR\fcontribution\x12\x1f\n" +
	"\vspread_desc\x18\r \x01(\tR\n" +
	"spreadDesc\x12\x1b\n" +
	"\ttail_icon\x18\x0e \x01(\x04R\btailIcon\x12!\n" +
	"\ftrigger_time\x18\x0f \x01(\x04R\vtriggerTime\x12%\n" +
	"\x0eprivilege_type\x18\x10 \x01(\x04R\rprivilegeType\x12$\n" +
	"\x0ecore_user_type\x18\x11 \x01(\x04R\fcoreUserType\x12\x1b\n" +
	"\ttail_text\x18\x12 \x01(\tR\btailText\x12V\n" +
	"\x0fcontribution_v2\x18\x13 \x01(\v2-.bilibili.interact_word_v2.ContributionInfoV2R\x0econtributionV2\x12K\n" +
	"\vgroup_medal\x18\x14 \x01(\v2*.bilibili.interact_word_v2.GroupMedalBriefR\n" +
	"groupMedal\x12\x1d\n" +
	"\n" +
	"is_mystery\x18\x15 \x01(\bR\tisMystery\x129\n" +
	"\x05uinfo\x18\x16 \x01(\v2#.bilibili.interact_word_v2.UserInfoR\x05uinfo\x12R\n" +
	"\rrelation_tail\x18\x17 \x01(\v2-.bilibili.interact_word_v2.UserAnchorRelationR\frelationTail\"(\n" +
	"\x10ContributionInfo\x12\x14\n" +
	"\x05grade\x18\x01 \x01(\x03R\x05grade\"[\n" +
	"\x12ContributionInfoV2\x12\x14\n" +
	"\x05grade\x18\x01 \x01(\x04R\x05grade\x12\x1b\n" +
	"\trank_type\x18\x02 \x01(\tR\brankType\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\xbd\x03\n" +
	"\rFansMedalInfo\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vmedal_level\x18\x02 \x01(\x03R\n" +
	"medalLevel\x12\x1d\n" +
	"\n" +
	"medal_name\x18\x03 \x01(\tR\tmedalName\x12\x1f\n" +
	"\vmedal_color\x18\x04 \x01(\x03R\n" +
	"medalColor\x12*\n" +
	"\x11medal_color_start\x18\x05 \x01(\x03R\x0fmedalColorStart\x12&\n" +
	"\x0fmedal_color_end\x18\x06 \x01(\x03R\rmedalColorEnd\x12,\n" +
	"\x12medal_color_border\x18\a \x01(\x03R\x10medalColorBorder\x12\x1d\n" +
	"\n" +
	"is_lighted\x18\b \x01(\x03R\tisLighted\x12\x1f\n" +
	"\vguard_level\x18\t \x01(\x03R\n" +
	"guardLevel\x12\x18\n" +
	"\aspecial\x18\n" +
	" \x01(\tR\aspecial\x12\x17\n" +
	"\aicon_id\x18\v \x01(\x03R\x06iconId\x12#\n" +
	"\ranchor_roomid\x18\f \x01(\x03R\fanchorRoomid\x12\x14\n" +
	"\x05score\x18\r \x01(\x03R\x05score\"v\n" +
	"\x12UserAnchorRelation\x12\x1b\n" +
	"\ttail_icon\x18\x01 \x01(\tR\btailIcon\x12&\n" +
	"\x0ftail_guide_text\x18\x02 \x01(\tR\rtailGuideText\x12\x1b\n" +
	"\ttail_type\x18\x03 \x01(\x04R\btailType\"_\n" +
	"\x0fGroupMedalBrief\x12\x19\n" +
	"\bmedal_id\x18\x01 \x01(\x04R\amedalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_lighted\x18\x03 \x01(\x04R\tisLighted\"f\n" +
	"\bRiskCtrl\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12A\n" +
	"\x06policy\x18\x02 \x01(\x0e2).bilibili.interact_word_v2.RiskPolicyEnumR\x06policy\"O\n" +
	"\fRoomAnonCtrl\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2+.bilibili.interact_word_v2.RoomAnonTypeEnumR\x04type\"\x97\x02\n" +
	"\n" +
	"BaseOption\x12!\n" +
	"\fneed_mystery\x18\x01 \x01(\bR\vneedMystery\x12@\n" +
	"\trisk_ctrl\x18\x02 \x01(\v2#.bilibili.interact_word_v2.RiskCtrlR\briskCtrl\x12M\n" +
	"\x0eroom_anon_ctrl\x18\x03 \x01(\v2'.bilibili.interact_word_v2.RoomAnonCtrlR\froomAnonCtrl\x12U\n" +
	"\x11risk_ctrl_handles\x18\x04 \x03(\x0e2).bilibili.interact_word_v2.RiskPolicyEnumR\x0friskCtrlHandles\"n\n" +
	"\vGuardOption\x12\x12\n" +
	"\x04ruid\x18\x01 \x01(\x03R\x04ruid\x12&\n" +
	"\x0fuse_local_cache\x18\x02 \x01(\bR\ruseLocalCache\x12#\n" +
	"\rstrong_depend\x18\x03 \x01(\bR\fstrongDepend\"z\n" +
	"\fWealthOption\x12\x16\n" +
	"\x06roomid\x18\x01 \x01(\x03R\x06roomid\x12\x19\n" +
	"\bview_uid\x18\x02 \x01(\x03R\aviewUid\x12\x12\n" +
	"\x04ruid\x18\x03 \x01(\x03R\x04ruid\x12#\n" +
	"\rstrong_depend\x18\x04 \x01(\bR\fstrongDepend\"\xc1\x01\n" +
	"\vMedalOption\x126\n" +
	"\x03typ\x18\x01 \x01(\x0e2$.bilibili.interact_word_v2.MedalTypeR\x03typ\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\x12\x1d\n" +
	"\n" +
	"need_guard\x18\x03 \x01(\bR\tneedGuard\x12#\n" +
	"\rstrong_depend\x18\x04 \x01(\bR\fstrongDepend\x12\x1d\n" +
	"\n" +
	"need_group\x18\x05 \x01(\bR\tneedGroup\"@\n" +
	"\x11GuardLeaderOption\x12\x12\n" +
	"\x04ruid\x18\x01 \x01(\x03R\x04ruid\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\"M\n" +
	"\vTitleOption\x12\x19\n" +
	"\brooom_id\x18\x01 \x01(\x03R\arooomId\x12#\n" +
	"\rstrong_depend\x18\x02 \x01(\bR\fstrongDepend\"6\n" +
	"\fRiskCtrlInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04face\x18\x02 \x01(\tR\x04face\"5\n" +
	"\vAccountInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04face\x18\x02 \x01(\tR\x04face\"`\n" +
	"\fOfficialInfo\x12\x12\n" +
	"\x04role\x18\x01 \x01(\x04R\x04role\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x04R\x04type\"\xf8\x02\n" +
	"\x04Base\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04face\x18\x02 \x01(\tR\x04face\x12\x1d\n" +
	"\n" +
	"name_color\x18\x03 \x01(\x05R\tnameColor\x12\x1d\n" +
	"\n" +
	"is_mystery\x18\x04 \x01(\bR\tisMystery\x12M\n" +
	"\x0erisk_ctrl_info\x18\x05 \x01(\v2'.bilibili.interact_word_v2.RiskCtrlInfoR\friskCtrlInfo\x12G\n" +
	"\vorigin_info\x18\x06 \x01(\v2&.bilibili.interact_word_v2.AccountInfoR\n" +
	"originInfo\x12L\n" +
	"\rofficial_info\x18\a \x01(\v2'.bilibili.interact_word_v2.OfficialInfoR\fofficialInfo\x12$\n" +
	"\x0ename_color_str\x18\b \x01(\tR\fnameColorStr\"\xca\x03\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x123\n" +
	"\x04base\x18\x02 \x01(\v2\x1f.bilibili.interact_word_v2.BaseR\x04base\x126\n" +
	"\x05medal\x18\x03 \x01(\v2 .bilibili.interact_word_v2.MedalR\x05medal\x129\n" +
	"\x06wealth\x18\x04 \x01(\v2!.bilibili.interact_word_v2.WealthR\x06wealth\x126\n" +
	"\x05title\x18\x05 \x01(\v2 .bilibili.interact_word_v2.TitleR\x05title\x126\n" +
	"\x05guard\x18\x06 \x01(\v2 .bilibili.interact_word_v2.GuardR\x05guard\x12I\n" +
	"\vuhead_frame\x18\a \x01(\v2(.bilibili.interact_word_v2.UserHeadFrameR\n" +
	"uheadFrame\x12I\n" +
	"\fguard_leader\x18\b \x01(\v2&.bilibili.interact_word_v2.GuardLeaderR\vguardLeader\"\xb7\x05\n" +
	"\x05Medal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x03R\x05level\x12\x1f\n" +
	"\vcolor_start\x18\x03 \x01(\x03R\n" +
	"colorStart\x12\x1b\n" +
	"\tcolor_end\x18\x04 \x01(\x03R\bcolorEnd\x12!\n" +
	"\fcolor_border\x18\x05 \x01(\x03R\vcolorBorder\x12\x14\n" +
	"\x05color\x18\x06 \x01(\x03R\x05color\x12\x0e\n" +
	"\x02id\x18\a \x01(\x03R\x02id\x12:\n" +
	"\x03typ\x18\b \x01(\x0e2(.bilibili.interact_word_v2.HaveMedalTypeR\x03typ\x12\x19\n" +
	"\bis_light\x18\t \x01(\x03R\aisLight\x12\x12\n" +
	"\x04ruid\x18\n" +
	" \x01(\x03R\x04ruid\x12\x1f\n" +
	"\vguard_level\x18\v \x01(\x03R\n" +
	"guardLevel\x12\x14\n" +
	"\x05score\x18\f \x01(\x03R\x05score\x12\x1d\n" +
	"\n" +
	"guard_icon\x18\r \x01(\tR\tguardIcon\x12\x1d\n" +
	"\n" +
	"honor_icon\x18\x0e \x01(\tR\thonorIcon\x12/\n" +
	"\x14v2_medal_color_start\x18\x0f \x01(\tR\x11v2MedalColorStart\x12+\n" +
	"\x12v2_medal_color_end\x18\x10 \x01(\tR\x0fv2MedalColorEnd\x121\n" +
	"\x15v2_medal_color_border\x18\x11 \x01(\tR\x12v2MedalColorBorder\x12-\n" +
	"\x13v2_medal_color_text\x18\x12 \x01(\tR\x10v2MedalColorText\x12/\n" +
	"\x14v2_medal_color_level\x18\x13 \x01(\tR\x11v2MedalColorLevel\x12,\n" +
	"\x12user_receive_count\x18\x14 \x01(\x03R\x10userReceiveCount\">\n" +
	"\x06Wealth\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x03R\x05level\x12\x1e\n" +
	"\vdm_icon_key\x18\x02 \x01(\tR\tdmIconKey\"M\n" +
	"\x05Title\x12$\n" +
	"\rOldTitleCssId\x18\x01 \x01(\tR\rOldTitleCssId\x12\x1e\n" +
	"\n" +
	"TitleCssId\x18\x02 \x01(\tR\n" +
	"TitleCssId\">\n" +
	"\x05Guard\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x03R\x05level\x12\x1f\n" +
	"\vexpired_str\x18\x02 \x01(\tR\n" +
	"expiredStr\"<\n" +
	"\rUserHeadFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tframe_img\x18\x02 \x01(\tR\bframeImg\"5\n" +
	"\vGuardLeader\x12&\n" +
	"\x0fis_guard_leader\x18\x01 \x01(\bR\risGuardLeader*X\n" +
	"\x0eRiskPolicyEnum\x12\r\n" +
	"\tRP_NORMAL\x10\x00\x12\r\n" +
	"\tRP_POLICY\x10\x01\x12\x0e\n" +
	"\n" +
	"RP_SILENCE\x10\x02\x12\n" +
	"\n" +
	"\x06RP_CNY\x10\x03\x12\f\n" +
	"\bRP_BIGEV\x10\x04*+\n" +
	"\tMedalType\x12\x0e\n" +
	"\n" +
	"Medal_Wear\x10\x00\x12\x0e\n" +
	"\n" +
	"Medal_Spec\x10\x01*2\n" +
	"\rHaveMedalType\x12\x10\n" +
	"\fMedal_Common\x10\x00\x12\x0f\n" +
	"\vMedal_Group\x10\x01*3\n" +
	"\x10RoomAnonTypeEnum\x12\n" +
	"\n" +
	"\x06RA_ALL\x10\x00\x12\x13\n" +
	"\x0fRA_With_Subject\x10\x01B]Z[github.com/zxc7563598/bilibili-live-assistant/pkg/bilibili/internal/protobuf/interactwordv2b\x06proto3"

var (
	file_INTERACT_WORD_V2_proto_rawDescOnce sync.Once
	file_INTERACT_WORD_V2_proto_rawDescData []byte
)

func file_INTERACT_WORD_V2_proto_rawDescGZIP() []byte {
	file_INTERACT_WORD_V2_proto_rawDescOnce.Do(func() {
		file_INTERACT_WORD_V2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_INTERACT_WORD_V2_proto_rawDesc), len(file_INTERACT_WORD_V2_proto_rawDesc)))
	})
	return file_INTERACT_WORD_V2_proto_rawDescData
}

var file_INTERACT_WORD_V2_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_INTERACT_WORD_V2_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_INTERACT_WORD_V2_proto_goTypes = []any{
	(RiskPolicyEnum)(0),        // 0: bilibili.interact_word_v2.RiskPolicyEnum
	(MedalType)(0),             // 1: bilibili.interact_word_v2.MedalType
	(HaveMedalType)(0),         // 2: bilibili.interact_word_v2.HaveMedalType
	(RoomAnonTypeEnum)(0),      // 3: bilibili.interact_word_v2.RoomAnonTypeEnum
	(*InteractWordV2)(nil),     // 4: bilibili.interact_word_v2.InteractWordV2
	(*ContributionInfo)(nil),   // 5: bilibili.interact_word_v2.ContributionInfo
	(*ContributionInfoV2)(nil), // 6: bilibili.interact_word_v2.ContributionInfoV2
	(*FansMedalInfo)(nil),      // 7: bilibili.interact_word_v2.FansMedalInfo
	(*UserAnchorRelation)(nil), // 8: bilibili.interact_word_v2.UserAnchorRelation
	(*GroupMedalBrief)(nil),    // 9: bilibili.interact_word_v2.GroupMedalBrief
	(*RiskCtrl)(nil),           // 10: bilibili.interact_word_v2.RiskCtrl
	(*RoomAnonCtrl)(nil),       // 11: bilibili.interact_word_v2.RoomAnonCtrl
	(*BaseOption)(nil),         // 12: bilibili.interact_word_v2.BaseOption
	(*GuardOption)(nil),        // 13: bilibili.interact_word_v2.GuardOption
	(*WealthOption)(nil),       // 14: bilibili.interact_word_v2.WealthOption
	(*MedalOption)(nil),        // 15: bilibili.interact_word_v2.MedalOption
	(*GuardLeaderOption)(nil),  // 16: bilibili.interact_word_v2.GuardLeaderOption
	(*TitleOption)(nil),        // 17: bilibili.interact_word_v2.TitleOption
	(*RiskCtrlInfo)(nil),       // 18: bilibili.interact_word_v2.RiskCtrlInfo
	(*AccountInfo)(nil),        // 19: bilibili.interact_word_v2.AccountInfo
	(*OfficialInfo)(nil),       // 20: bilibili.interact_word_v2.OfficialInfo
	(*Base)(nil),               // 21: bilibili.interact_word_v2.Base
	(*UserInfo)(nil),           // 22: bilibili.interact_word_v2.UserInfo
	(*Medal)(nil),              // 23: bilibili.interact_word_v2.Medal
	(*Wealth)(nil),             // 24: bilibili.interact_word_v2.Wealth
	(*Title)(nil),              // 25: bilibili.interact_word_v2.Title
	(*Guard)(nil),              // 26: bilibili.interact_word_v2.Guard
	(*UserHeadFrame)(nil),      // 27: bilibili.interact_word_v2.UserHeadFrame
	(*GuardLeader)(nil),        // 28: bilibili.interact_word_v2.GuardLeader
}
var file_INTERACT_WORD_V2_proto_depIdxs = []int32{
	7,  // 0: bilibili.interact_word_v2.InteractWordV2.fans_medal:type_name -> bilibili.interact_word_v2.FansMedalInfo
	5,  // 1: bilibili.interact_word_v2.InteractWordV2.contribution:type_name -> bilibili.interact_word_v2.ContributionInfo
	6,  // 2: bilibili.interact_word_v2.InteractWordV2.contribution_v2:type_name -> bilibili.interact_word_v2.ContributionInfoV2
	9,  // 3: bilibili.interact_word_v2.InteractWordV2.group_medal:type_name -> bilibili.interact_word_v2.GroupMedalBrief
	22, // 4: bilibili.interact_word_v2.InteractWordV2.uinfo:type_name -> bilibili.interact_word_v2.UserInfo
	8,  // 5: bilibili.interact_word_v2.InteractWordV2.relation_tail:type_name -> bilibili.interact_word_v2.UserAnchorRelation
	0,  // 6: bilibili.interact_word_v2.RiskCtrl.policy:type_name -> bilibili.interact_word_v2.RiskPolicyEnum
	3,  // 7: bilibili.interact_word_v2.RoomAnonCtrl.type:type_name -> bilibili.interact_word_v2.RoomAnonTypeEnum
	10, // 8: bilibili.interact_word_v2.BaseOption.risk_ctrl:type_name -> bilibili.interact_word_v2.RiskCtrl
	11, // 9: bilibili.interact_word_v2.BaseOption.room_anon_ctrl:type_name -> bilibili.interact_word_v2.RoomAnonCtrl
	0,  // 10: bilibili.interact_word_v2.BaseOption.risk_ctrl_handles:type_name -> bilibili.interact_word_v2.RiskPolicyEnum
	1,  // 11: bilibili.interact_word_v2.MedalOption.typ:type_name -> bilibili.interact_word_v2.MedalType
	18, // 12: bilibili.interact_word_v2.Base.risk_ctrl_info:type_name -> bilibili.interact_word_v2.RiskCtrlInfo
	19, // 13: bilibili.interact_word_v2.Base.origin_info:type_name -> bilibili.interact_word_v2.AccountInfo
	20, // 14: bilibili.interact_word_v2.Base.official_info:type_name -> bilibili.interact_word_v2.OfficialInfo
	21, // 15: bilibili.interact_word_v2.UserInfo.base:type_name -> bilibili.interact_word_v2.Base
	23, // 16: bilibili.interact_word_v2.UserInfo.medal:type_name -> bilibili.interact_word_v2.Medal
	24, // 17: bilibili.interact_word_v2.UserInfo.wealth:type_name -> bilibili.interact_word_v2.Wealth
	25, // 18: bilibili.interact_word_v2.UserInfo.title:type_name -> bilibili.interact_word_v2.Title
	26, // 19: bilibili.interact_word_v2.UserInfo.guard:type_name -> bilibili.interact_word_v2.Guard
	27, // 20: bilibili.interact_word_v2.UserInfo.uhead_frame:type_name -> bilibili.interact_word_v2.UserHeadFrame
	28, // 21: bilibili.interact_word_v2.UserInfo.guard_leader:type_name -> bilibili.interact_word_v2.GuardLeader
	2,  // 22: bilibili.interact_word_v2.Medal.typ:type_name -> bilibili.interact_word_v2.HaveMedalType
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_INTERACT_WORD_V2_proto_init() }
func file_INTERACT_WORD_V2_proto_init() {
	if File_INTERACT_WORD_V2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_INTERACT_WORD_V2_proto_rawDesc), len(file_INTERACT_WORD_V2_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_INTERACT_WORD_V2_proto_goTypes,
		DependencyIndexes: file_INTERACT_WORD_V2_proto_depIdxs,
		EnumInfos:         file_INTERACT_WORD_V2_proto_enumTypes,
		MessageInfos:      file_INTERACT_WORD_V2_proto_msgTypes,
	}.Build()
	File_INTERACT_WORD_V2_proto = out.File
	file_INTERACT_WORD_V2_proto_goTypes = nil
	file_INTERACT_WORD_V2_proto_depIdxs = nil
}
