export default {
  getOrderList: (page, status) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const orders = [
          {
            id: 'PO20260820001',
            title: '无线蓝牙耳机 主动降噪',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 12800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 2,
            statusText: '已发货',
            time: '2026-08-20 14:32',
          },
          {
            id: 'PO20260815002',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730003',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260815004',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730005',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260815006',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730007',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260820008',
            title: '无线蓝牙耳机 主动降噪',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 12800,
            type: 1,
            count: 1,
            sku: ['星空灰'],
            status: 2,
            statusText: '已发货',
            time: '2026-08-20 14:32',
          },
          {
            id: 'PO20260815009',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730010',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260815011',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730012',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260815013',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730014',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260820015',
            title: '无线蓝牙耳机 主动降噪',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 12800,
            type: 1,
            count: 1,
            sku: ['星空灰'],
            status: 2,
            statusText: '已发货',
            time: '2026-08-20 14:32',
          },
          {
            id: 'PO20260815016',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730017',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260815018',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730019',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
          {
            id: 'PO20260815020',
            title: '316 不锈钢保温杯 500ml',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 6800,
            type: 1,
            count: 1,
            sku: ['白色', '玩偶'],
            status: 1,
            statusText: '待发货',
            time: '2026-08-15 09:12',
          },
          {
            id: 'PO20260730021',
            title: '智能运动手环',
            cover: 'https://danmusuite.hejunjie.life/dist/avatar.jpg',
            amount: 360,
            type: 0,
            count: 1,
            sku: ['pro款', '黑色'],
            status: 3,
            statusText: '已完成',
            time: '2026-07-30 20:05',
          },
        ]
        const list = status === 0 ? orders : orders.filter(o => o.status === status)
        resolve({
          code: 0,
          data: {
            total: list.length * 2,
            pageData: list,
          },
          msg: 'success',
        })
      }, 1500)
    })
  },
}
