// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: SEND_GIFT_V2.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HaveMedalType int32

const (
	HaveMedalType_Medal_Common HaveMedalType = 0
	HaveMedalType_Medal_Group  HaveMedalType = 1
)

// Enum value maps for HaveMedalType.
var (
	HaveMedalType_name = map[int32]string{
		0: "Medal_Common",
		1: "Medal_Group",
	}
	HaveMedalType_value = map[string]int32{
		"Medal_Common": 0,
		"Medal_Group":  1,
	}
)

func (x HaveMedalType) Enum() *HaveMedalType {
	p := new(HaveMedalType)
	*p = x
	return p
}

func (x HaveMedalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HaveMedalType) Descriptor() protoreflect.EnumDescriptor {
	return file_SEND_GIFT_V2_proto_enumTypes[0].Descriptor()
}

func (HaveMedalType) Type() protoreflect.EnumType {
	return &file_SEND_GIFT_V2_proto_enumTypes[0]
}

func (x HaveMedalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HaveMedalType.Descriptor instead.
func (HaveMedalType) EnumDescriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{0}
}

type SendGiftV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname         string                 `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	Face          string                 `protobuf:"bytes,3,opt,name=face,proto3" json:"face,omitempty"`
	NameColor     string                 `protobuf:"bytes,4,opt,name=name_color,json=nameColor,proto3" json:"name_color,omitempty"`
	GuardLevel    int64                  `protobuf:"varint,5,opt,name=guard_level,json=guardLevel,proto3" json:"guard_level,omitempty"`
	SvgaBlock     int64                  `protobuf:"varint,6,opt,name=svga_block,json=svgaBlock,proto3" json:"svga_block,omitempty"`
	SendMaster    *SendMaster            `protobuf:"bytes,7,opt,name=send_master,json=sendMaster,proto3" json:"send_master,omitempty"`
	MedalInfo     *MedalInfo             `protobuf:"bytes,8,opt,name=medal_info,json=medalInfo,proto3" json:"medal_info,omitempty"`
	BlindGift     *BlindGift             `protobuf:"bytes,9,opt,name=blind_gift,json=blindGift,proto3" json:"blind_gift,omitempty"`
	GiftList      *GiftItem              `protobuf:"bytes,10,opt,name=gift_list,json=giftList,proto3" json:"gift_list,omitempty"`
	Switch        bool                   `protobuf:"varint,11,opt,name=switch,proto3" json:"switch,omitempty"`
	Test          int64                  `protobuf:"varint,12,opt,name=test,proto3" json:"test,omitempty"`
	WealthInfo    *WealthInfo            `protobuf:"bytes,13,opt,name=wealth_info,json=wealthInfo,proto3" json:"wealth_info,omitempty"`
	GroupMedal    *GroupMedalBrief       `protobuf:"bytes,14,opt,name=group_medal,json=groupMedal,proto3" json:"group_medal,omitempty"`
	SenderUinfo   *UserInfo              `protobuf:"bytes,15,opt,name=sender_uinfo,json=senderUinfo,proto3" json:"sender_uinfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGiftV2) Reset() {
	*x = SendGiftV2{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGiftV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGiftV2) ProtoMessage() {}

func (x *SendGiftV2) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGiftV2.ProtoReflect.Descriptor instead.
func (*SendGiftV2) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{0}
}

func (x *SendGiftV2) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SendGiftV2) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *SendGiftV2) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *SendGiftV2) GetNameColor() string {
	if x != nil {
		return x.NameColor
	}
	return ""
}

func (x *SendGiftV2) GetGuardLevel() int64 {
	if x != nil {
		return x.GuardLevel
	}
	return 0
}

func (x *SendGiftV2) GetSvgaBlock() int64 {
	if x != nil {
		return x.SvgaBlock
	}
	return 0
}

func (x *SendGiftV2) GetSendMaster() *SendMaster {
	if x != nil {
		return x.SendMaster
	}
	return nil
}

func (x *SendGiftV2) GetMedalInfo() *MedalInfo {
	if x != nil {
		return x.MedalInfo
	}
	return nil
}

func (x *SendGiftV2) GetBlindGift() *BlindGift {
	if x != nil {
		return x.BlindGift
	}
	return nil
}

func (x *SendGiftV2) GetGiftList() *GiftItem {
	if x != nil {
		return x.GiftList
	}
	return nil
}

func (x *SendGiftV2) GetSwitch() bool {
	if x != nil {
		return x.Switch
	}
	return false
}

func (x *SendGiftV2) GetTest() int64 {
	if x != nil {
		return x.Test
	}
	return 0
}

func (x *SendGiftV2) GetWealthInfo() *WealthInfo {
	if x != nil {
		return x.WealthInfo
	}
	return nil
}

func (x *SendGiftV2) GetGroupMedal() *GroupMedalBrief {
	if x != nil {
		return x.GroupMedal
	}
	return nil
}

func (x *SendGiftV2) GetSenderUinfo() *UserInfo {
	if x != nil {
		return x.SenderUinfo
	}
	return nil
}

type GiftItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GiftId             int64                  `protobuf:"varint,1,opt,name=gift_id,json=giftId,proto3" json:"gift_id,omitempty"`
	GiftName           string                 `protobuf:"bytes,2,opt,name=gift_name,json=giftName,proto3" json:"gift_name,omitempty"`
	Num                int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Demarcation        int64                  `protobuf:"varint,4,opt,name=demarcation,proto3" json:"demarcation,omitempty"`
	Price              int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice      int64                  `protobuf:"varint,6,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	TotalCoin          int64                  `protobuf:"varint,7,opt,name=total_coin,json=totalCoin,proto3" json:"total_coin,omitempty"`
	CoinType           string                 `protobuf:"bytes,8,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	Tid                string                 `protobuf:"bytes,9,opt,name=tid,proto3" json:"tid,omitempty"`
	Timestamp          int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SuperBatchGiftNum  int64                  `protobuf:"varint,11,opt,name=super_batch_gift_num,json=superBatchGiftNum,proto3" json:"super_batch_gift_num,omitempty"`
	BatchComboId       string                 `protobuf:"bytes,12,opt,name=batch_combo_id,json=batchComboId,proto3" json:"batch_combo_id,omitempty"`
	ComboResourcesId   int64                  `protobuf:"varint,13,opt,name=combo_resources_id,json=comboResourcesId,proto3" json:"combo_resources_id,omitempty"`
	ComboTotalCoin     int64                  `protobuf:"varint,14,opt,name=combo_total_coin,json=comboTotalCoin,proto3" json:"combo_total_coin,omitempty"`
	ComboStayTime      int64                  `protobuf:"varint,15,opt,name=combo_stay_time,json=comboStayTime,proto3" json:"combo_stay_time,omitempty"`
	Magnification      float32                `protobuf:"fixed32,16,opt,name=magnification,proto3" json:"magnification,omitempty"`
	ShowBatchComboSend bool                   `protobuf:"varint,17,opt,name=show_batch_combo_send,json=showBatchComboSend,proto3" json:"show_batch_combo_send,omitempty"`
	Action             string                 `protobuf:"bytes,18,opt,name=action,proto3" json:"action,omitempty"`
	EffectBlock        int64                  `protobuf:"varint,19,opt,name=effect_block,json=effectBlock,proto3" json:"effect_block,omitempty"`
	IsSpecialBatch     int64                  `protobuf:"varint,20,opt,name=is_special_batch,json=isSpecialBatch,proto3" json:"is_special_batch,omitempty"`
	FloatScResourceId  int64                  `protobuf:"varint,21,opt,name=float_sc_resource_id,json=floatScResourceId,proto3" json:"float_sc_resource_id,omitempty"`
	TagImage           string                 `protobuf:"bytes,22,opt,name=tag_image,json=tagImage,proto3" json:"tag_image,omitempty"`
	CritProb           int64                  `protobuf:"varint,23,opt,name=crit_prob,json=critProb,proto3" json:"crit_prob,omitempty"`
	Rcost              int64                  `protobuf:"varint,24,opt,name=rcost,proto3" json:"rcost,omitempty"`
	Test               int64                  `protobuf:"varint,25,opt,name=test,proto3" json:"test,omitempty"`
	FaceEffectType     int64                  `protobuf:"varint,26,opt,name=face_effect_type,json=faceEffectType,proto3" json:"face_effect_type,omitempty"`
	FaceEffectId       int64                  `protobuf:"varint,27,opt,name=face_effect_id,json=faceEffectId,proto3" json:"face_effect_id,omitempty"`
	IsNaming           bool                   `protobuf:"varint,28,opt,name=is_naming,json=isNaming,proto3" json:"is_naming,omitempty"`
	ReceiveUserInfo    *ReceiveUserInfo       `protobuf:"bytes,29,opt,name=receive_user_info,json=receiveUserInfo,proto3" json:"receive_user_info,omitempty"`
	IsJoinReceiver     bool                   `protobuf:"varint,30,opt,name=is_join_receiver,json=isJoinReceiver,proto3" json:"is_join_receiver,omitempty"`
	BagGift            *BagGiftInfo           `protobuf:"bytes,31,opt,name=bag_gift,json=bagGift,proto3" json:"bag_gift,omitempty"`
	GiftTag            []int64                `protobuf:"varint,32,rep,packed,name=gift_tag,json=giftTag,proto3" json:"gift_tag,omitempty"`
	ReceiverUinfo      *UserInfo              `protobuf:"bytes,33,opt,name=receiver_uinfo,json=receiverUinfo,proto3" json:"receiver_uinfo,omitempty"`
	FaceEffectV2       *FaceEffectV2          `protobuf:"bytes,34,opt,name=face_effect_v2,json=faceEffectV2,proto3" json:"face_effect_v2,omitempty"`
	GiftInfo           *GiftMaterialSnapShot  `protobuf:"bytes,35,opt,name=gift_info,json=giftInfo,proto3" json:"gift_info,omitempty"`
	GiftTipPrice       int64                  `protobuf:"varint,36,opt,name=gift_tip_price,json=giftTipPrice,proto3" json:"gift_tip_price,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GiftItem) Reset() {
	*x = GiftItem{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftItem) ProtoMessage() {}

func (x *GiftItem) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftItem.ProtoReflect.Descriptor instead.
func (*GiftItem) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{1}
}

func (x *GiftItem) GetGiftId() int64 {
	if x != nil {
		return x.GiftId
	}
	return 0
}

func (x *GiftItem) GetGiftName() string {
	if x != nil {
		return x.GiftName
	}
	return ""
}

func (x *GiftItem) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GiftItem) GetDemarcation() int64 {
	if x != nil {
		return x.Demarcation
	}
	return 0
}

func (x *GiftItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GiftItem) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *GiftItem) GetTotalCoin() int64 {
	if x != nil {
		return x.TotalCoin
	}
	return 0
}

func (x *GiftItem) GetCoinType() string {
	if x != nil {
		return x.CoinType
	}
	return ""
}

func (x *GiftItem) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *GiftItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GiftItem) GetSuperBatchGiftNum() int64 {
	if x != nil {
		return x.SuperBatchGiftNum
	}
	return 0
}

func (x *GiftItem) GetBatchComboId() string {
	if x != nil {
		return x.BatchComboId
	}
	return ""
}

func (x *GiftItem) GetComboResourcesId() int64 {
	if x != nil {
		return x.ComboResourcesId
	}
	return 0
}

func (x *GiftItem) GetComboTotalCoin() int64 {
	if x != nil {
		return x.ComboTotalCoin
	}
	return 0
}

func (x *GiftItem) GetComboStayTime() int64 {
	if x != nil {
		return x.ComboStayTime
	}
	return 0
}

func (x *GiftItem) GetMagnification() float32 {
	if x != nil {
		return x.Magnification
	}
	return 0
}

func (x *GiftItem) GetShowBatchComboSend() bool {
	if x != nil {
		return x.ShowBatchComboSend
	}
	return false
}

func (x *GiftItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GiftItem) GetEffectBlock() int64 {
	if x != nil {
		return x.EffectBlock
	}
	return 0
}

func (x *GiftItem) GetIsSpecialBatch() int64 {
	if x != nil {
		return x.IsSpecialBatch
	}
	return 0
}

func (x *GiftItem) GetFloatScResourceId() int64 {
	if x != nil {
		return x.FloatScResourceId
	}
	return 0
}

func (x *GiftItem) GetTagImage() string {
	if x != nil {
		return x.TagImage
	}
	return ""
}

func (x *GiftItem) GetCritProb() int64 {
	if x != nil {
		return x.CritProb
	}
	return 0
}

func (x *GiftItem) GetRcost() int64 {
	if x != nil {
		return x.Rcost
	}
	return 0
}

func (x *GiftItem) GetTest() int64 {
	if x != nil {
		return x.Test
	}
	return 0
}

func (x *GiftItem) GetFaceEffectType() int64 {
	if x != nil {
		return x.FaceEffectType
	}
	return 0
}

func (x *GiftItem) GetFaceEffectId() int64 {
	if x != nil {
		return x.FaceEffectId
	}
	return 0
}

func (x *GiftItem) GetIsNaming() bool {
	if x != nil {
		return x.IsNaming
	}
	return false
}

func (x *GiftItem) GetReceiveUserInfo() *ReceiveUserInfo {
	if x != nil {
		return x.ReceiveUserInfo
	}
	return nil
}

func (x *GiftItem) GetIsJoinReceiver() bool {
	if x != nil {
		return x.IsJoinReceiver
	}
	return false
}

func (x *GiftItem) GetBagGift() *BagGiftInfo {
	if x != nil {
		return x.BagGift
	}
	return nil
}

func (x *GiftItem) GetGiftTag() []int64 {
	if x != nil {
		return x.GiftTag
	}
	return nil
}

func (x *GiftItem) GetReceiverUinfo() *UserInfo {
	if x != nil {
		return x.ReceiverUinfo
	}
	return nil
}

func (x *GiftItem) GetFaceEffectV2() *FaceEffectV2 {
	if x != nil {
		return x.FaceEffectV2
	}
	return nil
}

func (x *GiftItem) GetGiftInfo() *GiftMaterialSnapShot {
	if x != nil {
		return x.GiftInfo
	}
	return nil
}

func (x *GiftItem) GetGiftTipPrice() int64 {
	if x != nil {
		return x.GiftTipPrice
	}
	return 0
}

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Face          string                 `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	NameColor     int32                  `protobuf:"varint,3,opt,name=name_color,json=nameColor,proto3" json:"name_color,omitempty"`
	IsMystery     bool                   `protobuf:"varint,4,opt,name=is_mystery,json=isMystery,proto3" json:"is_mystery,omitempty"`
	RiskCtrlInfo  *RiskCtrlInfo          `protobuf:"bytes,5,opt,name=risk_ctrl_info,json=riskCtrlInfo,proto3" json:"risk_ctrl_info,omitempty"`
	OriginInfo    *AccountInfo           `protobuf:"bytes,6,opt,name=origin_info,json=originInfo,proto3" json:"origin_info,omitempty"`
	OfficialInfo  *OfficialInfo          `protobuf:"bytes,7,opt,name=official_info,json=officialInfo,proto3" json:"official_info,omitempty"`
	NameColorStr  string                 `protobuf:"bytes,8,opt,name=name_color_str,json=nameColorStr,proto3" json:"name_color_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{2}
}

func (x *Base) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Base) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *Base) GetNameColor() int32 {
	if x != nil {
		return x.NameColor
	}
	return 0
}

func (x *Base) GetIsMystery() bool {
	if x != nil {
		return x.IsMystery
	}
	return false
}

func (x *Base) GetRiskCtrlInfo() *RiskCtrlInfo {
	if x != nil {
		return x.RiskCtrlInfo
	}
	return nil
}

func (x *Base) GetOriginInfo() *AccountInfo {
	if x != nil {
		return x.OriginInfo
	}
	return nil
}

func (x *Base) GetOfficialInfo() *OfficialInfo {
	if x != nil {
		return x.OfficialInfo
	}
	return nil
}

func (x *Base) GetNameColorStr() string {
	if x != nil {
		return x.NameColorStr
	}
	return ""
}

type Medal struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level              int64                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	ColorStart         int64                  `protobuf:"varint,3,opt,name=color_start,json=colorStart,proto3" json:"color_start,omitempty"`
	ColorEnd           int64                  `protobuf:"varint,4,opt,name=color_end,json=colorEnd,proto3" json:"color_end,omitempty"`
	ColorBorder        int64                  `protobuf:"varint,5,opt,name=color_border,json=colorBorder,proto3" json:"color_border,omitempty"`
	Color              int64                  `protobuf:"varint,6,opt,name=color,proto3" json:"color,omitempty"`
	Id                 int64                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	Typ                HaveMedalType          `protobuf:"varint,8,opt,name=typ,proto3,enum=HaveMedalType" json:"typ,omitempty"`
	IsLight            int64                  `protobuf:"varint,9,opt,name=is_light,json=isLight,proto3" json:"is_light,omitempty"`
	Ruid               int64                  `protobuf:"varint,10,opt,name=ruid,proto3" json:"ruid,omitempty"`
	GuardLevel         int64                  `protobuf:"varint,11,opt,name=guard_level,json=guardLevel,proto3" json:"guard_level,omitempty"`
	Score              int64                  `protobuf:"varint,12,opt,name=score,proto3" json:"score,omitempty"`
	GuardIcon          string                 `protobuf:"bytes,13,opt,name=guard_icon,json=guardIcon,proto3" json:"guard_icon,omitempty"`
	HonorIcon          string                 `protobuf:"bytes,14,opt,name=honor_icon,json=honorIcon,proto3" json:"honor_icon,omitempty"`
	V2MedalColorStart  string                 `protobuf:"bytes,15,opt,name=v2_medal_color_start,json=v2MedalColorStart,proto3" json:"v2_medal_color_start,omitempty"`
	V2MedalColorEnd    string                 `protobuf:"bytes,16,opt,name=v2_medal_color_end,json=v2MedalColorEnd,proto3" json:"v2_medal_color_end,omitempty"`
	V2MedalColorBorder string                 `protobuf:"bytes,17,opt,name=v2_medal_color_border,json=v2MedalColorBorder,proto3" json:"v2_medal_color_border,omitempty"`
	V2MedalColorText   string                 `protobuf:"bytes,18,opt,name=v2_medal_color_text,json=v2MedalColorText,proto3" json:"v2_medal_color_text,omitempty"`
	V2MedalColorLevel  string                 `protobuf:"bytes,19,opt,name=v2_medal_color_level,json=v2MedalColorLevel,proto3" json:"v2_medal_color_level,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Medal) Reset() {
	*x = Medal{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Medal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Medal) ProtoMessage() {}

func (x *Medal) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Medal.ProtoReflect.Descriptor instead.
func (*Medal) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{3}
}

func (x *Medal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Medal) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Medal) GetColorStart() int64 {
	if x != nil {
		return x.ColorStart
	}
	return 0
}

func (x *Medal) GetColorEnd() int64 {
	if x != nil {
		return x.ColorEnd
	}
	return 0
}

func (x *Medal) GetColorBorder() int64 {
	if x != nil {
		return x.ColorBorder
	}
	return 0
}

func (x *Medal) GetColor() int64 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Medal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Medal) GetTyp() HaveMedalType {
	if x != nil {
		return x.Typ
	}
	return HaveMedalType_Medal_Common
}

func (x *Medal) GetIsLight() int64 {
	if x != nil {
		return x.IsLight
	}
	return 0
}

func (x *Medal) GetRuid() int64 {
	if x != nil {
		return x.Ruid
	}
	return 0
}

func (x *Medal) GetGuardLevel() int64 {
	if x != nil {
		return x.GuardLevel
	}
	return 0
}

func (x *Medal) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Medal) GetGuardIcon() string {
	if x != nil {
		return x.GuardIcon
	}
	return ""
}

func (x *Medal) GetHonorIcon() string {
	if x != nil {
		return x.HonorIcon
	}
	return ""
}

func (x *Medal) GetV2MedalColorStart() string {
	if x != nil {
		return x.V2MedalColorStart
	}
	return ""
}

func (x *Medal) GetV2MedalColorEnd() string {
	if x != nil {
		return x.V2MedalColorEnd
	}
	return ""
}

func (x *Medal) GetV2MedalColorBorder() string {
	if x != nil {
		return x.V2MedalColorBorder
	}
	return ""
}

func (x *Medal) GetV2MedalColorText() string {
	if x != nil {
		return x.V2MedalColorText
	}
	return ""
}

func (x *Medal) GetV2MedalColorLevel() string {
	if x != nil {
		return x.V2MedalColorLevel
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Base          *Base                  `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Medal         *Medal                 `protobuf:"bytes,3,opt,name=medal,proto3" json:"medal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UserInfo) GetMedal() *Medal {
	if x != nil {
		return x.Medal
	}
	return nil
}

type ReceiveUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uname         string                 `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveUserInfo) Reset() {
	*x = ReceiveUserInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveUserInfo) ProtoMessage() {}

func (x *ReceiveUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveUserInfo.ProtoReflect.Descriptor instead.
func (*ReceiveUserInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveUserInfo) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *ReceiveUserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type SendMaster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname         string                 `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMaster) Reset() {
	*x = SendMaster{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMaster) ProtoMessage() {}

func (x *SendMaster) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMaster.ProtoReflect.Descriptor instead.
func (*SendMaster) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{6}
}

func (x *SendMaster) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SendMaster) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

type BlindGift struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BlindGiftConfigId int64                  `protobuf:"varint,1,opt,name=blind_gift_config_id,json=blindGiftConfigId,proto3" json:"blind_gift_config_id,omitempty"`
	OriginalGiftId    int64                  `protobuf:"varint,2,opt,name=original_gift_id,json=originalGiftId,proto3" json:"original_gift_id,omitempty"`
	OriginalGiftName  string                 `protobuf:"bytes,3,opt,name=original_gift_name,json=originalGiftName,proto3" json:"original_gift_name,omitempty"`
	From              int64                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	GiftAction        string                 `protobuf:"bytes,5,opt,name=gift_action,json=giftAction,proto3" json:"gift_action,omitempty"`
	OriginalGiftPrice int64                  `protobuf:"varint,6,opt,name=original_gift_price,json=originalGiftPrice,proto3" json:"original_gift_price,omitempty"`
	GiftTipPrice      int64                  `protobuf:"varint,7,opt,name=gift_tip_price,json=giftTipPrice,proto3" json:"gift_tip_price,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlindGift) Reset() {
	*x = BlindGift{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlindGift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindGift) ProtoMessage() {}

func (x *BlindGift) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindGift.ProtoReflect.Descriptor instead.
func (*BlindGift) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{7}
}

func (x *BlindGift) GetBlindGiftConfigId() int64 {
	if x != nil {
		return x.BlindGiftConfigId
	}
	return 0
}

func (x *BlindGift) GetOriginalGiftId() int64 {
	if x != nil {
		return x.OriginalGiftId
	}
	return 0
}

func (x *BlindGift) GetOriginalGiftName() string {
	if x != nil {
		return x.OriginalGiftName
	}
	return ""
}

func (x *BlindGift) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BlindGift) GetGiftAction() string {
	if x != nil {
		return x.GiftAction
	}
	return ""
}

func (x *BlindGift) GetOriginalGiftPrice() int64 {
	if x != nil {
		return x.OriginalGiftPrice
	}
	return 0
}

func (x *BlindGift) GetGiftTipPrice() int64 {
	if x != nil {
		return x.GiftTipPrice
	}
	return 0
}

type MedalInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetId         int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Special          string                 `protobuf:"bytes,2,opt,name=special,proto3" json:"special,omitempty"`
	AnchorUname      string                 `protobuf:"bytes,3,opt,name=anchor_uname,json=anchorUname,proto3" json:"anchor_uname,omitempty"`
	AnchorRoomid     int64                  `protobuf:"varint,4,opt,name=anchor_roomid,json=anchorRoomid,proto3" json:"anchor_roomid,omitempty"`
	MedalLevel       int64                  `protobuf:"varint,5,opt,name=medal_level,json=medalLevel,proto3" json:"medal_level,omitempty"`
	MedalName        string                 `protobuf:"bytes,6,opt,name=medal_name,json=medalName,proto3" json:"medal_name,omitempty"`
	MedalColor       int64                  `protobuf:"varint,7,opt,name=medal_color,json=medalColor,proto3" json:"medal_color,omitempty"`
	MedalColorStart  int64                  `protobuf:"varint,8,opt,name=medal_color_start,json=medalColorStart,proto3" json:"medal_color_start,omitempty"`
	MedalColorEnd    int64                  `protobuf:"varint,9,opt,name=medal_color_end,json=medalColorEnd,proto3" json:"medal_color_end,omitempty"`
	MedalColorBorder int64                  `protobuf:"varint,10,opt,name=medal_color_border,json=medalColorBorder,proto3" json:"medal_color_border,omitempty"`
	IsLighted        int64                  `protobuf:"varint,11,opt,name=is_lighted,json=isLighted,proto3" json:"is_lighted,omitempty"`
	GuardLevel       int64                  `protobuf:"varint,12,opt,name=guard_level,json=guardLevel,proto3" json:"guard_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MedalInfo) Reset() {
	*x = MedalInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedalInfo) ProtoMessage() {}

func (x *MedalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedalInfo.ProtoReflect.Descriptor instead.
func (*MedalInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{8}
}

func (x *MedalInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MedalInfo) GetSpecial() string {
	if x != nil {
		return x.Special
	}
	return ""
}

func (x *MedalInfo) GetAnchorUname() string {
	if x != nil {
		return x.AnchorUname
	}
	return ""
}

func (x *MedalInfo) GetAnchorRoomid() int64 {
	if x != nil {
		return x.AnchorRoomid
	}
	return 0
}

func (x *MedalInfo) GetMedalLevel() int64 {
	if x != nil {
		return x.MedalLevel
	}
	return 0
}

func (x *MedalInfo) GetMedalName() string {
	if x != nil {
		return x.MedalName
	}
	return ""
}

func (x *MedalInfo) GetMedalColor() int64 {
	if x != nil {
		return x.MedalColor
	}
	return 0
}

func (x *MedalInfo) GetMedalColorStart() int64 {
	if x != nil {
		return x.MedalColorStart
	}
	return 0
}

func (x *MedalInfo) GetMedalColorEnd() int64 {
	if x != nil {
		return x.MedalColorEnd
	}
	return 0
}

func (x *MedalInfo) GetMedalColorBorder() int64 {
	if x != nil {
		return x.MedalColorBorder
	}
	return 0
}

func (x *MedalInfo) GetIsLighted() int64 {
	if x != nil {
		return x.IsLighted
	}
	return 0
}

func (x *MedalInfo) GetGuardLevel() int64 {
	if x != nil {
		return x.GuardLevel
	}
	return 0
}

type BagGiftInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowPrice     int32                  `protobuf:"varint,1,opt,name=show_price,json=showPrice,proto3" json:"show_price,omitempty"`
	PriceForShow  int64                  `protobuf:"varint,2,opt,name=price_for_show,json=priceForShow,proto3" json:"price_for_show,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagGiftInfo) Reset() {
	*x = BagGiftInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagGiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagGiftInfo) ProtoMessage() {}

func (x *BagGiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagGiftInfo.ProtoReflect.Descriptor instead.
func (*BagGiftInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{9}
}

func (x *BagGiftInfo) GetShowPrice() int32 {
	if x != nil {
		return x.ShowPrice
	}
	return 0
}

func (x *BagGiftInfo) GetPriceForShow() int64 {
	if x != nil {
		return x.PriceForShow
	}
	return 0
}

type WealthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int64                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WealthInfo) Reset() {
	*x = WealthInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WealthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WealthInfo) ProtoMessage() {}

func (x *WealthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WealthInfo.ProtoReflect.Descriptor instead.
func (*WealthInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{10}
}

func (x *WealthInfo) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type FaceEffectV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceEffectV2) Reset() {
	*x = FaceEffectV2{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceEffectV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceEffectV2) ProtoMessage() {}

func (x *FaceEffectV2) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceEffectV2.ProtoReflect.Descriptor instead.
func (*FaceEffectV2) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{11}
}

func (x *FaceEffectV2) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FaceEffectV2) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GroupMedalBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedalId       int64                  `protobuf:"varint,1,opt,name=medal_id,json=medalId,proto3" json:"medal_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsLighted     int64                  `protobuf:"varint,3,opt,name=is_lighted,json=isLighted,proto3" json:"is_lighted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMedalBrief) Reset() {
	*x = GroupMedalBrief{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMedalBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMedalBrief) ProtoMessage() {}

func (x *GroupMedalBrief) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMedalBrief.ProtoReflect.Descriptor instead.
func (*GroupMedalBrief) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{12}
}

func (x *GroupMedalBrief) GetMedalId() int64 {
	if x != nil {
		return x.MedalId
	}
	return 0
}

func (x *GroupMedalBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupMedalBrief) GetIsLighted() int64 {
	if x != nil {
		return x.IsLighted
	}
	return 0
}

type GiftMaterialSnapShot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImgBasic      string                 `protobuf:"bytes,1,opt,name=img_basic,json=imgBasic,proto3" json:"img_basic,omitempty"`
	Webp          string                 `protobuf:"bytes,2,opt,name=webp,proto3" json:"webp,omitempty"`
	EffectId      int64                  `protobuf:"varint,3,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	HasImagedGift int64                  `protobuf:"varint,4,opt,name=has_imaged_gift,json=hasImagedGift,proto3" json:"has_imaged_gift,omitempty"`
	ImgGif        string                 `protobuf:"bytes,5,opt,name=img_gif,json=imgGif,proto3" json:"img_gif,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiftMaterialSnapShot) Reset() {
	*x = GiftMaterialSnapShot{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftMaterialSnapShot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftMaterialSnapShot) ProtoMessage() {}

func (x *GiftMaterialSnapShot) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftMaterialSnapShot.ProtoReflect.Descriptor instead.
func (*GiftMaterialSnapShot) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{13}
}

func (x *GiftMaterialSnapShot) GetImgBasic() string {
	if x != nil {
		return x.ImgBasic
	}
	return ""
}

func (x *GiftMaterialSnapShot) GetWebp() string {
	if x != nil {
		return x.Webp
	}
	return ""
}

func (x *GiftMaterialSnapShot) GetEffectId() int64 {
	if x != nil {
		return x.EffectId
	}
	return 0
}

func (x *GiftMaterialSnapShot) GetHasImagedGift() int64 {
	if x != nil {
		return x.HasImagedGift
	}
	return 0
}

func (x *GiftMaterialSnapShot) GetImgGif() string {
	if x != nil {
		return x.ImgGif
	}
	return ""
}

type RiskCtrlInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Face          string                 `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskCtrlInfo) Reset() {
	*x = RiskCtrlInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskCtrlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskCtrlInfo) ProtoMessage() {}

func (x *RiskCtrlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskCtrlInfo.ProtoReflect.Descriptor instead.
func (*RiskCtrlInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{14}
}

func (x *RiskCtrlInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiskCtrlInfo) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

type AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Face          string                 `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{15}
}

func (x *AccountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountInfo) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

type OfficialInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          int32                  `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfficialInfo) Reset() {
	*x = OfficialInfo{}
	mi := &file_SEND_GIFT_V2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfficialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficialInfo) ProtoMessage() {}

func (x *OfficialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SEND_GIFT_V2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficialInfo.ProtoReflect.Descriptor instead.
func (*OfficialInfo) Descriptor() ([]byte, []int) {
	return file_SEND_GIFT_V2_proto_rawDescGZIP(), []int{16}
}

func (x *OfficialInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *OfficialInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OfficialInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *OfficialInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_SEND_GIFT_V2_proto protoreflect.FileDescriptor

const file_SEND_GIFT_V2_proto_rawDesc = "" +
	"\n" +
	"\x12SEND_GIFT_V2.proto\"\x8e\x04\n" +
	"\n" +
	"SendGiftV2\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05uname\x18\x02 \x01(\tR\x05uname\x12\x12\n" +
	"\x04face\x18\x03 \x01(\tR\x04face\x12\x1d\n" +
	"\n" +
	"name_color\x18\x04 \x01(\tR\tnameColor\x12\x1f\n" +
	"\vguard_level\x18\x05 \x01(\x03R\n" +
	"guardLevel\x12\x1d\n" +
	"\n" +
	"svga_block\x18\x06 \x01(\x03R\tsvgaBlock\x12,\n" +
	"\vsend_master\x18\a \x01(\v2\v.SendMasterR\n" +
	"sendMaster\x12)\n" +
	"\n" +
	"medal_info\x18\b \x01(\v2\n" +
	".MedalInfoR\tmedalInfo\x12)\n" +
	"\n" +
	"blind_gift\x18\t \x01(\v2\n" +
	".BlindGiftR\tblindGift\x12&\n" +
	"\tgift_list\x18\n" +
	" \x01(\v2\t.GiftItemR\bgiftList\x12\x16\n" +
	"\x06switch\x18\v \x01(\bR\x06switch\x12\x12\n" +
	"\x04test\x18\f \x01(\x03R\x04test\x12,\n" +
	"\vwealth_info\x18\r \x01(\v2\v.WealthInfoR\n" +
	"wealthInfo\x121\n" +
	"\vgroup_medal\x18\x0e \x01(\v2\x10.GroupMedalBriefR\n" +
	"groupMedal\x12,\n" +
	"\fsender_uinfo\x18\x0f \x01(\v2\t.UserInfoR\vsenderUinfo\"\xa1\n" +
	"\n" +
	"\bGiftItem\x12\x17\n" +
	"\agift_id\x18\x01 \x01(\x03R\x06giftId\x12\x1b\n" +
	"\tgift_name\x18\x02 \x01(\tR\bgiftName\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12 \n" +
	"\vdemarcation\x18\x04 \x01(\x03R\vdemarcation\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12%\n" +
	"\x0ediscount_price\x18\x06 \x01(\x03R\rdiscountPrice\x12\x1d\n" +
	"\n" +
	"total_coin\x18\a \x01(\x03R\ttotalCoin\x12\x1b\n" +
	"\tcoin_type\x18\b \x01(\tR\bcoinType\x12\x10\n" +
	"\x03tid\x18\t \x01(\tR\x03tid\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12/\n" +
	"\x14super_batch_gift_num\x18\v \x01(\x03R\x11superBatchGiftNum\x12$\n" +
	"\x0ebatch_combo_id\x18\f \x01(\tR\fbatchComboId\x12,\n" +
	"\x12combo_resources_id\x18\r \x01(\x03R\x10comboResourcesId\x12(\n" +
	"\x10combo_total_coin\x18\x0e \x01(\x03R\x0ecomboTotalCoin\x12&\n" +
	"\x0fcombo_stay_time\x18\x0f \x01(\x03R\rcomboStayTime\x12$\n" +
	"\rmagnification\x18\x10 \x01(\x02R\rmagnification\x121\n" +
	"\x15show_batch_combo_send\x18\x11 \x01(\bR\x12showBatchComboSend\x12\x16\n" +
	"\x06action\x18\x12 \x01(\tR\x06action\x12!\n" +
	"\feffect_block\x18\x13 \x01(\x03R\veffectBlock\x12(\n" +
	"\x10is_special_batch\x18\x14 \x01(\x03R\x0eisSpecialBatch\x12/\n" +
	"\x14float_sc_resource_id\x18\x15 \x01(\x03R\x11floatScResourceId\x12\x1b\n" +
	"\ttag_image\x18\x16 \x01(\tR\btagImage\x12\x1b\n" +
	"\tcrit_prob\x18\x17 \x01(\x03R\bcritProb\x12\x14\n" +
	"\x05rcost\x18\x18 \x01(\x03R\x05rcost\x12\x12\n" +
	"\x04test\x18\x19 \x01(\x03R\x04test\x12(\n" +
	"\x10face_effect_type\x18\x1a \x01(\x03R\x0efaceEffectType\x12$\n" +
	"\x0eface_effect_id\x18\x1b \x01(\x03R\ffaceEffectId\x12\x1b\n" +
	"\tis_naming\x18\x1c \x01(\bR\bisNaming\x12<\n" +
	"\x11receive_user_info\x18\x1d \x01(\v2\x10.ReceiveUserInfoR\x0freceiveUserInfo\x12(\n" +
	"\x10is_join_receiver\x18\x1e \x01(\bR\x0eisJoinReceiver\x12'\n" +
	"\bbag_gift\x18\x1f \x01(\v2\f.BagGiftInfoR\abagGift\x12\x19\n" +
	"\bgift_tag\x18  \x03(\x03R\agiftTag\x120\n" +
	"\x0ereceiver_uinfo\x18! \x01(\v2\t.UserInfoR\rreceiverUinfo\x123\n" +
	"\x0eface_effect_v2\x18\" \x01(\v2\r.FaceEffectV2R\ffaceEffectV2\x122\n" +
	"\tgift_info\x18# \x01(\v2\x15.GiftMaterialSnapShotR\bgiftInfo\x12$\n" +
	"\x0egift_tip_price\x18$ \x01(\x03R\fgiftTipPrice\"\xaa\x02\n" +
	"\x04Base\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04face\x18\x02 \x01(\tR\x04face\x12\x1d\n" +
	"\n" +
	"name_color\x18\x03 \x01(\x05R\tnameColor\x12\x1d\n" +
	"\n" +
	"is_mystery\x18\x04 \x01(\bR\tisMystery\x123\n" +
	"\x0erisk_ctrl_info\x18\x05 \x01(\v2\r.RiskCtrlInfoR\friskCtrlInfo\x12-\n" +
	"\vorigin_info\x18\x06 \x01(\v2\f.AccountInfoR\n" +
	"originInfo\x122\n" +
	"\rofficial_info\x18\a \x01(\v2\r.OfficialInfoR\fofficialInfo\x12$\n" +
	"\x0ename_color_str\x18\b \x01(\tR\fnameColorStr\"\xef\x04\n" +
	"\x05Medal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x03R\x05level\x12\x1f\n" +
	"\vcolor_start\x18\x03 \x01(\x03R\n" +
	"colorStart\x12\x1b\n" +
	"\tcolor_end\x18\x04 \x01(\x03R\bcolorEnd\x12!\n" +
	"\fcolor_border\x18\x05 \x01(\x03R\vcolorBorder\x12\x14\n" +
	"\x05color\x18\x06 \x01(\x03R\x05color\x12\x0e\n" +
	"\x02id\x18\a \x01(\x03R\x02id\x12 \n" +
	"\x03typ\x18\b \x01(\x0e2\x0e.HaveMedalTypeR\x03typ\x12\x19\n" +
	"\bis_light\x18\t \x01(\x03R\aisLight\x12\x12\n" +
	"\x04ruid\x18\n" +
	" \x01(\x03R\x04ruid\x12\x1f\n" +
	"\vguard_level\x18\v \x01(\x03R\n" +
	"guardLevel\x12\x14\n" +
	"\x05score\x18\f \x01(\x03R\x05score\x12\x1d\n" +
	"\n" +
	"guard_icon\x18\r \x01(\tR\tguardIcon\x12\x1d\n" +
	"\n" +
	"honor_icon\x18\x0e \x01(\tR\thonorIcon\x12/\n" +
	"\x14v2_medal_color_start\x18\x0f \x01(\tR\x11v2MedalColorStart\x12+\n" +
	"\x12v2_medal_color_end\x18\x10 \x01(\tR\x0fv2MedalColorEnd\x121\n" +
	"\x15v2_medal_color_border\x18\x11 \x01(\tR\x12v2MedalColorBorder\x12-\n" +
	"\x13v2_medal_color_text\x18\x12 \x01(\tR\x10v2MedalColorText\x12/\n" +
	"\x14v2_medal_color_level\x18\x13 \x01(\tR\x11v2MedalColorLevel\"U\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\x04base\x18\x02 \x01(\v2\x05.BaseR\x04base\x12\x1c\n" +
	"\x05medal\x18\x03 \x01(\v2\x06.MedalR\x05medal\"9\n" +
	"\x0fReceiveUserInfo\x12\x14\n" +
	"\x05uname\x18\x01 \x01(\tR\x05uname\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"4\n" +
	"\n" +
	"SendMaster\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05uname\x18\x02 \x01(\tR\x05uname\"\x9f\x02\n" +
	"\tBlindGift\x12/\n" +
	"\x14blind_gift_config_id\x18\x01 \x01(\x03R\x11blindGiftConfigId\x12(\n" +
	"\x10original_gift_id\x18\x02 \x01(\x03R\x0eoriginalGiftId\x12,\n" +
	"\x12original_gift_name\x18\x03 \x01(\tR\x10originalGiftName\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x03R\x04from\x12\x1f\n" +
	"\vgift_action\x18\x05 \x01(\tR\n" +
	"giftAction\x12.\n" +
	"\x13original_gift_price\x18\x06 \x01(\x03R\x11originalGiftPrice\x12$\n" +
	"\x0egift_tip_price\x18\a \x01(\x03R\fgiftTipPrice\"\xad\x03\n" +
	"\tMedalInfo\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x18\n" +
	"\aspecial\x18\x02 \x01(\tR\aspecial\x12!\n" +
	"\fanchor_uname\x18\x03 \x01(\tR\vanchorUname\x12#\n" +
	"\ranchor_roomid\x18\x04 \x01(\x03R\fanchorRoomid\x12\x1f\n" +
	"\vmedal_level\x18\x05 \x01(\x03R\n" +
	"medalLevel\x12\x1d\n" +
	"\n" +
	"medal_name\x18\x06 \x01(\tR\tmedalName\x12\x1f\n" +
	"\vmedal_color\x18\a \x01(\x03R\n" +
	"medalColor\x12*\n" +
	"\x11medal_color_start\x18\b \x01(\x03R\x0fmedalColorStart\x12&\n" +
	"\x0fmedal_color_end\x18\t \x01(\x03R\rmedalColorEnd\x12,\n" +
	"\x12medal_color_border\x18\n" +
	" \x01(\x03R\x10medalColorBorder\x12\x1d\n" +
	"\n" +
	"is_lighted\x18\v \x01(\x03R\tisLighted\x12\x1f\n" +
	"\vguard_level\x18\f \x01(\x03R\n" +
	"guardLevel\"R\n" +
	"\vBagGiftInfo\x12\x1d\n" +
	"\n" +
	"show_price\x18\x01 \x01(\x05R\tshowPrice\x12$\n" +
	"\x0eprice_for_show\x18\x02 \x01(\x03R\fpriceForShow\"\"\n" +
	"\n" +
	"WealthInfo\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x03R\x05level\"2\n" +
	"\fFaceEffectV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x03R\x04type\"_\n" +
	"\x0fGroupMedalBrief\x12\x19\n" +
	"\bmedal_id\x18\x01 \x01(\x03R\amedalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_lighted\x18\x03 \x01(\x03R\tisLighted\"\xa5\x01\n" +
	"\x14GiftMaterialSnapShot\x12\x1b\n" +
	"\timg_basic\x18\x01 \x01(\tR\bimgBasic\x12\x12\n" +
	"\x04webp\x18\x02 \x01(\tR\x04webp\x12\x1b\n" +
	"\teffect_id\x18\x03 \x01(\x03R\beffectId\x12&\n" +
	"\x0fhas_imaged_gift\x18\x04 \x01(\x03R\rhasImagedGift\x12\x17\n" +
	"\aimg_gif\x18\x05 \x01(\tR\x06imgGif\"6\n" +
	"\fRiskCtrlInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04face\x18\x02 \x01(\tR\x04face\"5\n" +
	"\vAccountInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04face\x18\x02 \x01(\tR\x04face\"`\n" +
	"\fOfficialInfo\x12\x12\n" +
	"\x04role\x18\x01 \x01(\x05R\x04role\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type*2\n" +
	"\rHaveMedalType\x12\x10\n" +
	"\fMedal_Common\x10\x00\x12\x0f\n" +
	"\vMedal_Group\x10\x01BNZLgithub.com/zxc7563598/bilibili-live-assistant/pkg/bilibili/internal/protobufb\x06proto3"

var (
	file_SEND_GIFT_V2_proto_rawDescOnce sync.Once
	file_SEND_GIFT_V2_proto_rawDescData []byte
)

func file_SEND_GIFT_V2_proto_rawDescGZIP() []byte {
	file_SEND_GIFT_V2_proto_rawDescOnce.Do(func() {
		file_SEND_GIFT_V2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SEND_GIFT_V2_proto_rawDesc), len(file_SEND_GIFT_V2_proto_rawDesc)))
	})
	return file_SEND_GIFT_V2_proto_rawDescData
}

var file_SEND_GIFT_V2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SEND_GIFT_V2_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_SEND_GIFT_V2_proto_goTypes = []any{
	(HaveMedalType)(0),           // 0: HaveMedalType
	(*SendGiftV2)(nil),           // 1: SendGiftV2
	(*GiftItem)(nil),             // 2: GiftItem
	(*Base)(nil),                 // 3: Base
	(*Medal)(nil),                // 4: Medal
	(*UserInfo)(nil),             // 5: UserInfo
	(*ReceiveUserInfo)(nil),      // 6: ReceiveUserInfo
	(*SendMaster)(nil),           // 7: SendMaster
	(*BlindGift)(nil),            // 8: BlindGift
	(*MedalInfo)(nil),            // 9: MedalInfo
	(*BagGiftInfo)(nil),          // 10: BagGiftInfo
	(*WealthInfo)(nil),           // 11: WealthInfo
	(*FaceEffectV2)(nil),         // 12: FaceEffectV2
	(*GroupMedalBrief)(nil),      // 13: GroupMedalBrief
	(*GiftMaterialSnapShot)(nil), // 14: GiftMaterialSnapShot
	(*RiskCtrlInfo)(nil),         // 15: RiskCtrlInfo
	(*AccountInfo)(nil),          // 16: AccountInfo
	(*OfficialInfo)(nil),         // 17: OfficialInfo
}
var file_SEND_GIFT_V2_proto_depIdxs = []int32{
	7,  // 0: SendGiftV2.send_master:type_name -> SendMaster
	9,  // 1: SendGiftV2.medal_info:type_name -> MedalInfo
	8,  // 2: SendGiftV2.blind_gift:type_name -> BlindGift
	2,  // 3: SendGiftV2.gift_list:type_name -> GiftItem
	11, // 4: SendGiftV2.wealth_info:type_name -> WealthInfo
	13, // 5: SendGiftV2.group_medal:type_name -> GroupMedalBrief
	5,  // 6: SendGiftV2.sender_uinfo:type_name -> UserInfo
	6,  // 7: GiftItem.receive_user_info:type_name -> ReceiveUserInfo
	10, // 8: GiftItem.bag_gift:type_name -> BagGiftInfo
	5,  // 9: GiftItem.receiver_uinfo:type_name -> UserInfo
	12, // 10: GiftItem.face_effect_v2:type_name -> FaceEffectV2
	14, // 11: GiftItem.gift_info:type_name -> GiftMaterialSnapShot
	15, // 12: Base.risk_ctrl_info:type_name -> RiskCtrlInfo
	16, // 13: Base.origin_info:type_name -> AccountInfo
	17, // 14: Base.official_info:type_name -> OfficialInfo
	0,  // 15: Medal.typ:type_name -> HaveMedalType
	3,  // 16: UserInfo.base:type_name -> Base
	4,  // 17: UserInfo.medal:type_name -> Medal
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_SEND_GIFT_V2_proto_init() }
func file_SEND_GIFT_V2_proto_init() {
	if File_SEND_GIFT_V2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SEND_GIFT_V2_proto_rawDesc), len(file_SEND_GIFT_V2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SEND_GIFT_V2_proto_goTypes,
		DependencyIndexes: file_SEND_GIFT_V2_proto_depIdxs,
		EnumInfos:         file_SEND_GIFT_V2_proto_enumTypes,
		MessageInfos:      file_SEND_GIFT_V2_proto_msgTypes,
	}.Build()
	File_SEND_GIFT_V2_proto = out.File
	file_SEND_GIFT_V2_proto_goTypes = nil
	file_SEND_GIFT_V2_proto_depIdxs = nil
}
